-- GENERATED by supabase/content/build-seed.mjs — edit the .mjs sources, not this file.
-- Фаза 2 content: grammar topics + exercises, reading texts. Safe to re-run (upserts).

insert into grammar_topics (unit, section, title, summary) values
  (1, 'Present', 'am/is/are', 'Глагол to be в настоящем времени: I am; he/she/it is; we/you/they are. Краткие формы: I''m, he''s, it''s, we''re, they''re. Отрицание — добавляем not: I''m not, he isn''t, they aren''t.'),
  (2, 'Present', 'am/is/are (questions)', 'В вопросе am/is/are встаёт перед подлежащим: Am I…? Is it…? Are you…? Вопросительное слово — в самом начале: Where is…? Короткие ответы: Yes, I am. / No, it isn''t. В утвердительном коротком ответе сокращать нельзя: Yes, I am (не Yes, I''m).'),
  (3, 'Present', 'I am doing (present continuous)', 'Present continuous = am/is/are + глагол с -ing. Так говорят о том, что происходит сейчас, в момент речи: I''m working. She isn''t listening. Орфография: write → writing (немая e выпадает), run → running (согласная удваивается), lie → lying.'),
  (4, 'Present', 'are you doing? (present continuous questions)', 'Вопрос в present continuous: am/is/are ставим перед подлежащим, затем глагол с -ing: Are you working? What is she doing? Where are they going? Короткие ответы: Yes, I am. / No, he isn''t.'),
  (5, 'Present', 'I do/work/like etc. (present simple)', 'Present simple: I/you/we/they work, но he/she/it works — в 3-м лице единственного числа добавляем -s. Время для того, что бывает регулярно, всегда или вообще верно: I work in IT. The office opens at nine. Орфография: после s, sh, ch, x, o пишем -es (watches, goes, does); согласная + y → -ies (study → studies); have → has.'),
  (6, 'Present', 'I don''t … (present simple negative)', 'Отрицание в present simple: I/you/we/they don''t + глагол; he/she/it doesn''t + глагол. После doesn''t глагол без -s: She doesn''t work (не doesn''t works). don''t = do not, doesn''t = does not.'),
  (7, 'Present', 'Do you …? (present simple questions)', 'Вопрос в present simple: Do + I/you/we/they + глагол? Does + he/she/it + глагол? После does глагол без -s: Does she work…? Вопросительное слово — в начале: Where do you live? What does it mean? Короткие ответы: Yes, I do. / No, she doesn''t.'),
  (8, 'Present', 'I am doing (present continuous) and I do (present simple)', 'Present continuous (am/is/are + -ing) — то, что происходит сейчас или в эти дни: I''m fixing a bug right now. Present simple — привычки, регулярные действия, факты: I fix bugs every day. Глаголы know, like, want, need, understand, mean, prefer, believe, remember обычно не ставят в continuous: I know (не I''m knowing).'),
  (9, 'Present', 'I have … and I''ve got …', 'Have и have got значат одно и то же — «иметь»: I have a laptop = I''ve got a laptop; he/she/it has = has got. Отрицание: I don''t have = I haven''t got. Вопрос: Do you have…? = Have you got…? Не смешивай формы: Do you have… (не Have you have…). В прошедшем времени только had: I had a cold last week.'),
  (10, 'Past', 'was/were', 'Прошедшее время глагола to be: I/he/she/it was; we/you/they were. Отрицание: wasn''t, weren''t. Вопрос: Was she…? Were you…? Короткие ответы: Yes, I was. / No, they weren''t.'),
  (11, 'Past', 'worked/got/went etc. (past simple)', 'Past simple — законченное действие в прошлом: I worked yesterday. Правильные глаголы получают -ed: work → worked, live → lived, stop → stopped, study → studied. Неправильные надо запомнить: go → went, get → got, have → had, see → saw, make → made, find → found, send → sent, write → wrote. Форма одна для всех лиц: I/he/they worked.'),
  (12, 'Past', 'I didn''t … Did you …? (past simple negative and questions)', 'Отрицание в past simple: didn''t + глагол в начальной форме, для всех лиц: I didn''t go (не didn''t went). Вопрос: Did + подлежащее + глагол: Did you see it? What did she say? Короткие ответы: Yes, I did. / No, they didn''t.'),
  (13, 'Past', 'I was doing (past continuous)', null),
  (14, 'Past', 'I was doing (past continuous) and I did (past simple)', null),
  (15, 'Present perfect', 'I have done (present perfect 1)', null),
  (16, 'Present perfect', 'I''ve just … I''ve already … I haven''t … yet (present perfect 2)', null),
  (17, 'Present perfect', 'Have you ever …? (present perfect 3)', null),
  (18, 'Present perfect', 'How long have you …? (present perfect 4)', null),
  (19, 'Present perfect', 'for, since, ago', null),
  (20, 'Present perfect', 'I have done (present perfect) and I did (past)', null),
  (21, 'Passive', 'is done, was done (passive 1)', null),
  (22, 'Passive', 'is being done, has been done (passive 2)', null),
  (23, 'Verb forms', 'be/have/do in present and past tenses', null),
  (24, 'Verb forms', 'Regular and irregular verbs', null),
  (25, 'Future', 'What are you doing tomorrow?', null),
  (26, 'Future', 'I''m going to …', null),
  (27, 'Future', 'will/shall 1', null),
  (28, 'Future', 'will/shall 2', null),
  (29, 'Modals, imperative etc.', 'might', null),
  (30, 'Modals, imperative etc.', 'can and could', null),
  (31, 'Modals, imperative etc.', 'must, mustn''t, don''t need to', null),
  (32, 'Modals, imperative etc.', 'should', null),
  (33, 'Modals, imperative etc.', 'I have to …', null),
  (34, 'Modals, imperative etc.', 'Would you like …? I''d like …', null),
  (35, 'Modals, imperative etc.', 'Do this! Don''t do that! Let''s do this!', null),
  (36, 'Modals, imperative etc.', 'I used to …', null),
  (37, 'There and it', 'there is, there are', null),
  (38, 'There and it', 'there was/were, there has/have been, there will be', null),
  (39, 'There and it', 'It …', null),
  (40, 'Auxiliary verbs', 'I am, I don''t etc.', null),
  (41, 'Auxiliary verbs', 'Have you? Are you? Don''t you? etc.', null),
  (42, 'Auxiliary verbs', 'too/either, so am I / neither do I etc.', null),
  (43, 'Auxiliary verbs', 'isn''t, haven''t, don''t etc. (negatives)', null),
  (44, 'Questions', 'is it …? have you …? do they …? etc. (questions 1)', null),
  (45, 'Questions', 'Who saw you? Who did you see? (questions 2)', null),
  (46, 'Questions', 'Who is she talking to? What is it like? (questions 3)', null),
  (47, 'Questions', 'What …? Which …? How …? (questions 4)', null),
  (48, 'Questions', 'How long does it take …?', null),
  (49, 'Questions', 'Do you know where …? I don''t know what … etc.', null),
  (50, 'Reported speech', 'She said that … He told me that …', null),
  (51, '-ing and to …', 'work/working, go/going, do/doing', null),
  (52, '-ing and to …', 'to … (I want to do) and -ing (I enjoy doing)', null),
  (53, '-ing and to …', 'I want you to … I told you to …', null),
  (54, '-ing and to …', 'I went to the shop to …', null),
  (55, 'Go, get, do, make and have', 'go to …, go on …, go for …, go -ing', null),
  (56, 'Go, get, do, make and have', 'get', null),
  (57, 'Go, get, do, make and have', 'do and make', null),
  (58, 'Go, get, do, make and have', 'have', null),
  (59, 'Pronouns and possessives', 'I/me, he/him, they/them etc.', null),
  (60, 'Pronouns and possessives', 'my/his/their etc.', null),
  (61, 'Pronouns and possessives', 'Whose is this? It''s mine/yours/hers etc.', null),
  (62, 'Pronouns and possessives', 'I/me/my/mine', null),
  (63, 'Pronouns and possessives', 'myself/yourself/themselves etc.', null),
  (64, 'Pronouns and possessives', '-''s (Kate''s camera / my brother''s car etc.)', null),
  (65, 'A and the', 'a/an …', null),
  (66, 'A and the', 'train(s), bus(es) (singular and plural)', null),
  (67, 'A and the', 'a bottle / some water (countable/uncountable 1)', null),
  (68, 'A and the', 'a cake / some cake / some cakes (countable/uncountable 2)', null),
  (69, 'A and the', 'a/an and the', null),
  (70, 'A and the', 'the …', null),
  (71, 'A and the', 'go to work, go home, go to the cinema', null),
  (72, 'A and the', 'I like music, I hate exams', null),
  (73, 'A and the', 'the … (names of places)', null),
  (74, 'Determiners and pronouns', 'this/that/these/those', null),
  (75, 'Determiners and pronouns', 'one/ones', null),
  (76, 'Determiners and pronouns', 'some and any', null),
  (77, 'Determiners and pronouns', 'not + any, no, none', null),
  (78, 'Determiners and pronouns', 'not + anybody/anyone/anything, nobody/no-one/nothing', null),
  (79, 'Determiners and pronouns', 'somebody/anything/nowhere etc.', null),
  (80, 'Determiners and pronouns', 'every and all', null),
  (81, 'Determiners and pronouns', 'all, most, some, any, no/none', null),
  (82, 'Determiners and pronouns', 'both, either, neither', null),
  (83, 'Determiners and pronouns', 'a lot, much, many', null),
  (84, 'Determiners and pronouns', '(a) little, (a) few', null),
  (85, 'Adjectives and adverbs', 'old/nice/interesting etc. (adjectives)', null),
  (86, 'Adjectives and adverbs', 'quickly/badly/suddenly etc. (adverbs)', null),
  (87, 'Adjectives and adverbs', 'old/older, expensive/more expensive', null),
  (88, 'Adjectives and adverbs', 'older than …, more expensive than …', null),
  (89, 'Adjectives and adverbs', 'not as … as', null),
  (90, 'Adjectives and adverbs', 'the oldest, the most expensive', null),
  (91, 'Adjectives and adverbs', 'enough', null),
  (92, 'Adjectives and adverbs', 'too', null),
  (93, 'Word order', 'He speaks English very well. (word order 1)', null),
  (94, 'Word order', 'always/usually/often etc. (word order 2)', null),
  (95, 'Word order', 'still, yet, already', null),
  (96, 'Word order', 'Give me that book! Give it to me!', null),
  (97, 'Conjunctions and clauses', 'and, but, or, so, because', null),
  (98, 'Conjunctions and clauses', 'When …', null),
  (99, 'Conjunctions and clauses', 'If we go … If you see … etc.', null),
  (100, 'Conjunctions and clauses', 'If I had … If we went … etc.', null),
  (101, 'Conjunctions and clauses', 'a person who … a thing that/which … (relative clauses 1)', null),
  (102, 'Conjunctions and clauses', 'the people we met, the hotel you stayed at (relative clauses 2)', null),
  (103, 'Prepositions', 'at 8 o''clock, on Monday, in April', null),
  (104, 'Prepositions', 'from … to, until, since, for', null),
  (105, 'Prepositions', 'before, after, during, while', null),
  (106, 'Prepositions', 'in, at, on (places 1)', null),
  (107, 'Prepositions', 'in, at, on (places 2)', null),
  (108, 'Prepositions', 'to, in, at (places 3)', null),
  (109, 'Prepositions', 'under, behind, opposite etc.', null),
  (110, 'Prepositions', 'up, over, through etc.', null),
  (111, 'Prepositions', 'on, at, by, with, about', null),
  (112, 'Prepositions', 'afraid of …, good at … etc.; of/at/for etc. (prepositions) + -ing', null),
  (113, 'Prepositions', 'listen to …, look at … etc. (verb + preposition)', null),
  (114, 'Phrasal verbs', 'go in, fall off, run away etc. (phrasal verbs 1)', null),
  (115, 'Phrasal verbs', 'put on your shoes, put your shoes on (phrasal verbs 2)', null)
on conflict (unit) do update set section = excluded.section, title = excluded.title, summary = excluded.summary;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'My name ___ Alex.', array['am', 'is', 'are']::text[], 'is', array[]::text[], 'My name = it → is.'),
  (2, 'multiple_choice', 'I ___ a backend developer.', array['am', 'is', 'are']::text[], 'am', array[]::text[], 'С I всегда am.'),
  (3, 'multiple_choice', 'The servers ___ in Frankfurt.', array['am', 'is', 'are']::text[], 'are', array[]::text[], 'The servers — множественное число → are.'),
  (4, 'fill_blank', 'We ___ in the same team. (be)', null::text[], 'are', array['''re']::text[], 'We → are.'),
  (5, 'fill_blank', 'The build ___ ready yet. (be, отрицание)', null::text[], 'isn''t', array['is not']::text[], 'The build = it → is not / isn''t.'),
  (6, 'multiple_choice', 'You ___ late. The meeting starts at ten.', array['am not', 'isn''t', 'aren''t']::text[], 'aren''t', array[]::text[], 'You → are not / aren''t.'),
  (7, 'multiple_choice', 'It ___ cold in the office today.', array['am', 'is', 'are']::text[], 'is', array[]::text[], 'It → is.'),
  (8, 'fill_blank', 'My colleagues ___ from Brazil. (be)', null::text[], 'are', array[]::text[], 'My colleagues = they → are.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 1
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', '___ you a developer?', array['Am', 'Is', 'Are']::text[], 'Are', array[]::text[], 'Вопрос с you: Are you…?'),
  (2, 'multiple_choice', '___ the API down again?', array['Am', 'Is', 'Are']::text[], 'Is', array[]::text[], 'The API = it → Is it…?'),
  (3, 'multiple_choice', 'Where ___ my laptop?', array['am', 'is', 'are']::text[], 'is', array[]::text[], 'My laptop = it → Where is…?'),
  (4, 'multiple_choice', '''Are you busy?'' ''Yes, I ___.''', array['am', '''m', 'is']::text[], 'am', array[]::text[], 'В коротком утвердительном ответе не сокращаем: Yes, I am.'),
  (5, 'multiple_choice', '''Is the test green?'' ''No, it ___.''', array['isn''t', 'aren''t', 'not']::text[], 'isn''t', array[]::text[], 'Короткий отрицательный ответ: No, it isn''t.'),
  (6, 'fill_blank', 'How old ___ your computer? (be)', null::text[], 'is', array[]::text[], 'Your computer = it → is.'),
  (7, 'fill_blank', 'What ___ your colleagues'' names? (be)', null::text[], 'are', array[]::text[], 'Names — множественное число → are.'),
  (8, 'multiple_choice', '''Are they in the office?'' ''No, they ___.''', array['isn''t', 'aren''t', 'not']::text[], 'aren''t', array[]::text[], 'They → No, they aren''t.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 2
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'fill_blank', 'Please be quiet. I ___ on a bug. (work)', null::text[], 'am working', array['''m working']::text[], 'Сейчас, в момент речи: I am (I''m) working.'),
  (2, 'fill_blank', 'Look! The build ___. (run)', null::text[], 'is running', array['''s running']::text[], 'It is + running (n удваивается).'),
  (3, 'multiple_choice', 'She ___ code right now.', array['writes', 'is writing', 'writing']::text[], 'is writing', array[]::text[], 'right now → present continuous: is writing. Без is нельзя.'),
  (4, 'fill_blank', 'We ___ a new feature this week. (build)', null::text[], 'are building', array['''re building']::text[], 'Действие идёт в эти дни: we are (we''re) building.'),
  (5, 'multiple_choice', 'I ___ TV. You can turn it off.', array['am not watching', 'don''t watching', 'not watching']::text[], 'am not watching', array[]::text[], 'Отрицание: am not + -ing.'),
  (6, 'multiple_choice', 'Right now he ___ an email to the client.', array['is writeing', 'is writing', 'is writting']::text[], 'is writing', array[]::text[], 'write → writing: немая e выпадает, t не удваивается.'),
  (7, 'fill_blank', 'They ___ in the meeting room. (sit)', null::text[], 'are sitting', array['''re sitting']::text[], 'sit → sitting (t удваивается).'),
  (8, 'multiple_choice', 'It ___, so I''m working from home today.', array['is raining', 'rains', 'raining']::text[], 'is raining', array[]::text[], 'Дождь идёт сейчас → it is (it''s) raining.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 3
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', '___ you listening to me?', array['Are', 'Do', 'Is']::text[], 'Are', array[]::text[], 'You → Are you + -ing?'),
  (2, 'multiple_choice', 'What ___ she doing?', array['is', 'are', 'does']::text[], 'is', array[]::text[], 'She → What is she doing?'),
  (3, 'multiple_choice', 'Why ___ laughing?', array['are you', 'you are', 'do you']::text[], 'are you', array[]::text[], 'В вопросе are ставим перед подлежащим: Why are you…?'),
  (4, 'multiple_choice', '''Is Anna working today?'' ''No, she ___.''', array['isn''t', 'doesn''t', 'not']::text[], 'isn''t', array[]::text[], 'Вопрос с is → ответ No, she isn''t.'),
  (5, 'multiple_choice', 'Where ___ going?', array['are they', 'they are', 'do they']::text[], 'are they', array[]::text[], 'Where are they going?'),
  (6, 'fill_blank', '___ the server restarting? (be)', null::text[], 'Is', array[]::text[], 'The server = it → Is it restarting?'),
  (7, 'multiple_choice', '''Are you using this monitor?'' ''Yes, I ___.''', array['am', 'do', '''m']::text[], 'am', array[]::text[], 'Yes, I am — без сокращения.'),
  (8, 'multiple_choice', 'What ___ on right now?', array['are you working', 'you are working', 'do you working']::text[], 'are you working', array[]::text[], 'What are you working on? — are перед you, глагол с -ing.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 4
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'She ___ in a big IT company.', array['work', 'works', 'working']::text[], 'works', array[]::text[], 'She → +s: works.'),
  (2, 'fill_blank', 'The office ___ at nine o''clock. (open)', null::text[], 'opens', array[]::text[], 'The office = it → opens.'),
  (3, 'fill_blank', 'He ___ his code before every commit. (test)', null::text[], 'tests', array[]::text[], 'He → tests. Регулярное действие — present simple.'),
  (4, 'fill_blank', 'My brother ___ computer science at university. (study)', null::text[], 'studies', array[]::text[], 'Согласная + y → -ies: studies.'),
  (5, 'fill_blank', 'Tom ___ to work by bike. (go)', null::text[], 'goes', array[]::text[], 'go → goes (после o добавляем -es).'),
  (6, 'multiple_choice', 'We ___ a standup every morning.', array['have', 'has', 'having']::text[], 'have', array[]::text[], 'We → have. Has только с he/she/it.'),
  (7, 'multiple_choice', 'The app ___ on Android and iOS.', array['run', 'runs', 'running']::text[], 'runs', array[]::text[], 'The app = it → runs.'),
  (8, 'fill_blank', 'Our team lead ___ every pull request. (review)', null::text[], 'reviews', array[]::text[], 'Our team lead = he/she → reviews.'),
  (9, 'fill_blank', 'He ___ two languages. (speak)', null::text[], 'speaks', array[]::text[], 'He → speaks.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 5
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'I ___ like long meetings.', array['don''t', 'doesn''t', 'not']::text[], 'don''t', array[]::text[], 'I → don''t.'),
  (2, 'multiple_choice', 'He ___ work on Fridays.', array['don''t', 'doesn''t', 'isn''t']::text[], 'doesn''t', array[]::text[], 'He → doesn''t + глагол.'),
  (3, 'multiple_choice', 'She doesn''t ___ Python.', array['know', 'knows', 'knowing']::text[], 'know', array[]::text[], 'После doesn''t глагол без -s.'),
  (4, 'fill_blank', 'This function ___ anything. (return, отрицание)', null::text[], 'doesn''t return', array['does not return']::text[], 'It → doesn''t return (без -s).'),
  (5, 'fill_blank', 'We ___ on weekends. (work, отрицание)', null::text[], 'don''t work', array['do not work']::text[], 'We → don''t work.'),
  (6, 'fill_blank', 'My laptop ___ a camera. (have, отрицание)', null::text[], 'doesn''t have', array['does not have']::text[], 'It → doesn''t have (не doesn''t has).'),
  (7, 'multiple_choice', 'The tests ___ on my machine.', array['don''t pass', 'doesn''t pass', 'not pass']::text[], 'don''t pass', array[]::text[], 'The tests = they → don''t pass.'),
  (8, 'multiple_choice', 'Paul ___ coffee.', array['doesn''t drink', 'don''t drink', 'doesn''t drinks']::text[], 'doesn''t drink', array[]::text[], 'Paul = he → doesn''t drink, глагол без -s.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 6
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', '___ you work from home?', array['Do', 'Does', 'Are']::text[], 'Do', array[]::text[], 'You → Do you + глагол?'),
  (2, 'multiple_choice', '___ this script run on Windows?', array['Do', 'Does', 'Is']::text[], 'Does', array[]::text[], 'This script = it → Does it run…?'),
  (3, 'multiple_choice', 'Where ___ your team lead live?', array['do', 'does', 'is']::text[], 'does', array[]::text[], 'Your team lead = he/she → Where does… live?'),
  (4, 'multiple_choice', 'What does this error ___?', array['mean', 'means', 'meaning']::text[], 'mean', array[]::text[], 'После does глагол без -s: What does it mean?'),
  (5, 'multiple_choice', '''Do you use Git?'' ''Yes, I ___.''', array['do', 'does', 'am']::text[], 'do', array[]::text[], 'Вопрос с do → Yes, I do.'),
  (6, 'multiple_choice', '''Does Anna speak English?'' ''No, she ___.''', array['don''t', 'doesn''t', 'isn''t']::text[], 'doesn''t', array[]::text[], 'Вопрос с does → No, she doesn''t.'),
  (7, 'fill_blank', 'How often ___ you deploy to production? (do/does)', null::text[], 'do', array[]::text[], 'You → do.'),
  (8, 'fill_blank', 'What time ___ the standup start? (do/does)', null::text[], 'does', array[]::text[], 'The standup = it → does.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 7
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'Be quiet! The team lead ___ on the phone.', array['talks', 'is talking', 'talk']::text[], 'is talking', array[]::text[], 'Прямо сейчас → present continuous.'),
  (2, 'multiple_choice', 'She usually ___ work at 8 a.m.', array['starts', 'is starting', 'start']::text[], 'starts', array[]::text[], 'usually — привычка → present simple, she → starts.'),
  (3, 'multiple_choice', 'I ___ what you mean.', array['understand', 'am understanding', 'understanding']::text[], 'understand', array[]::text[], 'understand не ставят в continuous.'),
  (4, 'multiple_choice', 'Look! Somebody ___ our demo right now.', array['watches', 'is watching', 'watch']::text[], 'is watching', array[]::text[], 'Look! / right now → present continuous.'),
  (5, 'multiple_choice', 'We ___ a release every two weeks.', array['do', 'are doing', 'does']::text[], 'do', array[]::text[], 'every two weeks — регулярно → present simple.'),
  (6, 'multiple_choice', '___ this word?', array['Do you know', 'Are you knowing', 'You know']::text[], 'Do you know', array[]::text[], 'know не бывает в continuous; вопрос — с do.'),
  (7, 'multiple_choice', 'Right now I ___ on the login page.', array['work', 'am working', 'works']::text[], 'am working', array[]::text[], 'Right now → I am (I''m) working.'),
  (8, 'multiple_choice', 'He ___ tea; he prefers coffee.', array['doesn''t like', 'isn''t liking', 'don''t like']::text[], 'doesn''t like', array[]::text[], 'like — глагол состояния → present simple, he → doesn''t.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 8
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'She ___ two monitors on her desk.', array['have', 'has', 'haves']::text[], 'has', array[]::text[], 'She → has.'),
  (2, 'multiple_choice', 'I''ve ___ a new laptop.', array['got', 'get', 'have']::text[], 'got', array[]::text[], 'I''ve got = I have.'),
  (3, 'multiple_choice', '___ you got a minute?', array['Have', 'Do', 'Has']::text[], 'Have', array[]::text[], 'Have you got…? (с got вопрос строится через have).'),
  (4, 'multiple_choice', 'Do you ___ a GitHub account?', array['have', 'has', 'got']::text[], 'have', array[]::text[], 'Do you have…? После do — have.'),
  (5, 'multiple_choice', 'He ___ got a car.', array['hasn''t', 'haven''t', 'doesn''t']::text[], 'hasn''t', array[]::text[], 'He → hasn''t got.'),
  (6, 'multiple_choice', 'We ___ much time before the deadline.', array['don''t have', 'doesn''t have', 'not have']::text[], 'don''t have', array[]::text[], 'We → don''t have.'),
  (7, 'multiple_choice', '''Has your phone got a good camera?'' ''Yes, it ___.''', array['has', 'have', 'does']::text[], 'has', array[]::text[], 'Вопрос с has → Yes, it has.'),
  (8, 'multiple_choice', 'Yesterday I ___ a headache.', array['had', 'have', 'have got']::text[], 'had', array[]::text[], 'В прошлом только had.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 9
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'I ___ at home yesterday.', array['was', 'were', 'am']::text[], 'was', array[]::text[], 'I → was.'),
  (2, 'multiple_choice', 'The servers ___ down last night.', array['was', 'were', 'are']::text[], 'were', array[]::text[], 'The servers = they → were.'),
  (3, 'multiple_choice', '___ you at the meeting on Monday?', array['Was', 'Were', 'Did']::text[], 'Were', array[]::text[], 'You → Were you…?'),
  (4, 'fill_blank', 'The weather ___ nice last weekend. (be, отрицание)', null::text[], 'wasn''t', array['was not']::text[], 'It → was not / wasn''t.'),
  (5, 'multiple_choice', 'Where ___ you at ten o''clock?', array['was', 'were', 'did']::text[], 'were', array[]::text[], 'You → were.'),
  (6, 'multiple_choice', '''Was the demo good?'' ''Yes, it ___.''', array['was', 'were', 'did']::text[], 'was', array[]::text[], 'Вопрос с was → Yes, it was.'),
  (7, 'fill_blank', 'We ___ tired after the release. (be)', null::text[], 'were', array[]::text[], 'We → were.'),
  (8, 'multiple_choice', 'Why ___ Tom late this morning?', array['was', 'were', 'did']::text[], 'was', array[]::text[], 'Tom = he → was.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 10
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'fill_blank', 'Yesterday I ___ until 7 p.m. (work)', null::text[], 'worked', array[]::text[], 'Правильный глагол: work → worked.'),
  (2, 'fill_blank', 'We ___ the bug last week. (fix)', null::text[], 'fixed', array[]::text[], 'fix → fixed.'),
  (3, 'fill_blank', 'She ___ to London in 2019. (go)', null::text[], 'went', array[]::text[], 'go — неправильный: went.'),
  (4, 'fill_blank', 'I ___ an email to the client this morning. (send)', null::text[], 'sent', array[]::text[], 'send — неправильный: sent.'),
  (5, 'fill_blank', 'The build ___ because of a missing file. (fail)', null::text[], 'failed', array[]::text[], 'fail → failed.'),
  (6, 'fill_blank', 'He ___ computer science at university. (study)', null::text[], 'studied', array[]::text[], 'Согласная + y → -ied: studied.'),
  (7, 'fill_blank', 'They ___ the meeting at 11 o''clock. (stop)', null::text[], 'stopped', array[]::text[], 'stop → stopped (p удваивается).'),
  (8, 'fill_blank', 'I ___ the answer on Stack Overflow. (find)', null::text[], 'found', array[]::text[], 'find — неправильный: found.'),
  (9, 'multiple_choice', 'Last year our team ___ a new app.', array['made', 'maked', 'make']::text[], 'made', array[]::text[], 'make — неправильный: made.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 11
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation
from (values
  (1, 'multiple_choice', 'I ___ the tests yesterday.', array['didn''t run', 'didn''t ran', 'not ran']::text[], 'didn''t run', array[]::text[], 'После didn''t — начальная форма: run.'),
  (2, 'multiple_choice', '___ you merge my pull request?', array['Did', 'Do', 'Were']::text[], 'Did', array[]::text[], 'Вопрос в прошедшем: Did you + глагол?'),
  (3, 'multiple_choice', 'Did she ___ the report?', array['send', 'sent', 'sends']::text[], 'send', array[]::text[], 'После did — начальная форма: send.'),
  (4, 'multiple_choice', 'What ___ the client say at yesterday''s meeting?', array['did', 'does', 'was']::text[], 'did', array[]::text[], 'yesterday → past simple: What did… say?'),
  (5, 'fill_blank', 'We ___ to the conference last year. (go, отрицание)', null::text[], 'didn''t go', array['did not go']::text[], 'didn''t + go (не didn''t went).'),
  (6, 'multiple_choice', '''Did you enjoy the course?'' ''Yes, I ___.''', array['did', 'was', 'enjoyed']::text[], 'did', array[]::text[], 'Вопрос с did → Yes, I did.'),
  (7, 'fill_blank', 'Where ___ you have lunch yesterday? (do/did)', null::text[], 'did', array[]::text[], 'yesterday → did.'),
  (8, 'multiple_choice', 'He ___ at the office last Friday.', array['didn''t work', 'doesn''t worked', 'didn''t worked']::text[], 'didn''t work', array[]::text[], 'didn''t + начальная форма: work.')
) as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)
join grammar_topics t on t.unit = 12
on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;

insert into texts (title, body, cefr_level, position, questions) values
  ('My Name Is Alex', 'Hello! My name is Alex. I am a developer. I work in a small team. There are five people in my team. We make software for online shops.

Every day I start work at nine o''clock. First, I read my email. Then we have a short meeting. We call it a standup. Each person answers three questions: What did I do yesterday? What will I do today? Do I have a problem?

After the standup, I write code. Sometimes I fix a bug. Sometimes I work on a new feature. I like my work because every day is different.', 'A1', 1, '[{"statement":"Alex works in a big team of fifty people.","answer":false},{"statement":"The standup is a short meeting.","answer":true}]'::jsonb),
  ('A Bug in the App', 'Maria is a tester. She tests the app before every release. Today she has a problem. The app does not open on her phone. She sees an error on the screen.

Maria writes a task for the team. In the task, she explains the problem: what she did, what she expected and what happened. She also adds a screenshot.

Ben is a backend developer. He reads the task and looks at the code. After one hour, he finds the bug. It is a small mistake in one function. Ben fixes it, and Maria tests the app again. Now it works!', 'A1', 2, '[{"statement":"Ben finds the bug in the code.","answer":true},{"statement":"Maria fixes the bug.","answer":false}]'::jsonb),
  ('Office or Home?', 'Our office is in the city centre. It is not big, but it is nice. There are ten desks, a kitchen and two meeting rooms.

I come to the office three days a week. On the other two days, I work from home. At home, I have a desk, a computer and a good chair. It is quiet, so I can think about my tasks.

In the office, I talk to my friends from the team. We have lunch together, and we often help each other with difficult questions. I think both are good: the office is for people, and home is for quiet work.', 'A1', 3, '[{"statement":"The writer works from home two days a week.","answer":true},{"statement":"The office has five meeting rooms.","answer":false}]'::jsonb),
  ('English for Work', 'Many developers need English. Documentation, error messages and questions on the internet are often in English. In many companies, the team speaks English at meetings too.

You don''t need perfect English to start. Try to learn a few new words every day, and read short texts about things you know. It is easier to understand a text about code than a text about history or art.

Practice is important. Listen to podcasts, write your commit messages in English and don''t be afraid of mistakes. Every week, your level improves a little.', 'A1', 4, '[{"statement":"You need perfect English before you start.","answer":false},{"statement":"It is easier to read about things you know.","answer":true}]'::jsonb),
  ('My First Week', 'Last month I started a new job. My first week was busy but interesting.

On Monday, I met the team and got my laptop. I didn''t write any code that day. I installed programs and read the documentation.

On Tuesday, my team lead explained the project to me. It is an app for doctors and their patients. I had a lot of questions, and she answered all of them.

On Wednesday, I fixed my first bug. It was very small, but I was happy. On Thursday, I made my first pull request, and on Friday, it went into the release. It was a good start!', 'A2', 5, '[{"statement":"On Monday, the writer wrote a lot of code.","answer":false},{"statement":"The writer''s first pull request went into the release on Friday.","answer":true}]'::jsonb),
  ('The Sprint', 'Our team works in sprints. A sprint is two weeks long. At the start of every sprint, we have a planning meeting. We look at the list of tasks and decide what we can finish in two weeks.

Every task has a size. Small tasks take one or two days, and big tasks take a week. We don''t take too many tasks, because we want to finish the sprint on time.

At the end of the sprint, we show our new features to the client. Then we have one more meeting and talk about the sprint: what went well, what went badly and what we can change next time.', 'A2', 6, '[{"statement":"A sprint is one month long.","answer":false},{"statement":"The team shows new features to the client at the end of the sprint.","answer":true}]'::jsonb),
  ('Why Do We Write Tests?', 'A test is a small program that checks another program. For example, a function adds two numbers. A test calls the function with 2 and 3 and checks that the answer is 5.

Why do developers write tests? Because code changes all the time. When you change one part of the app, you can break another part and not notice it. Tests run automatically after every commit and find these problems early.

Writing tests takes time, but it saves more time later. It is much cheaper to find a bug on your computer than in production, when real users see it.', 'A2', 7, '[{"statement":"Tests help to find problems early.","answer":true},{"statement":"Writing tests takes no time at all.","answer":false}]'::jsonb),
  ('What Is an API?', 'Many programs need to talk to each other. For example, a weather app on your phone does not know the weather. It asks a server. The app sends a request, and the server sends a response with the data.

The rules for this conversation are called an API. An API says what requests you can send and what responses you get back. Each address for a request is called an endpoint, for example /weather/today.

Some APIs are free. Others need a token — a secret key that shows who you are. Without the correct token, the server answers with an error.', 'A2', 8, '[{"statement":"The weather app knows the weather without a server.","answer":false},{"statement":"A token is a secret key.","answer":true}]'::jsonb),
  ('Git in Five Minutes', 'Git is a tool that saves the history of your code. The code and its history live in a repository.

When you start a new task, you usually create a branch. A branch is your own copy of the code, so your changes do not break the work of other people. When you finish a small step, you make a commit. A commit is like a photo of your code at one moment, with a short message about the change.

When the task is ready, you open a pull request. Your colleagues review the code and write comments. When everybody agrees, you merge the branch into the main code.', 'A2', 9, '[{"statement":"You usually create a branch for a new task.","answer":true},{"statement":"You merge the branch before the review.","answer":false}]'::jsonb),
  ('The Cache', 'Imagine a server that takes two seconds to answer a request. If a thousand users send the same request, the server does the same slow work a thousand times.

A cache helps with this problem. The first time, the server does the work and saves the answer in the cache. The next time somebody sends the same request, the server takes the answer from the cache. This is very fast.

But a cache has one danger: old data. If the data in the database changes, the answer in the cache is not correct anymore. So developers need to decide when to update the cache or remove old answers from it.', 'A2', 10, '[{"statement":"A cache can make answers faster.","answer":true},{"statement":"Data in a cache is always correct.","answer":false}]'::jsonb),
  ('A Bad Friday', 'Last Friday, at five o''clock in the evening, our website stopped working. Users saw an error page, and nobody could buy anything.

First, we looked at the logs. The server was fine, but the database was very slow. Then we found the problem: a new update sent the same request to the database thousands of times.

We didn''t try to fix the code on a Friday evening. Instead, we went back to the old version. After ten minutes, the website worked again. On Monday, we fixed the bug, added a test and deployed the update again.', 'A2', 11, '[{"statement":"The problem was in the requests to the database.","answer":true},{"statement":"The team fixed the code on Friday evening.","answer":false}]'::jsonb),
  ('An Email to the Client', 'Hi Sarah,

Thank you for your message. We looked at the problem with the login page yesterday. You were right: some users couldn''t log in from their phones. The reason was an old version of one library.

We updated the library and tested the login page on five different phones. Everything works now. The new version is on the test server today, and we plan to deploy it to production on Thursday.

Please let me know if you have any questions.

Best regards,
Alex', 'A2', 12, '[{"statement":"Some users couldn''t log in from their phones.","answer":true},{"statement":"The new version is already in production.","answer":false}]'::jsonb)
on conflict (title) do update set body = excluded.body, cefr_level = excluded.cefr_level, position = excluded.position, questions = excluded.questions;

-- Link each text to the dictionary words it contains (headword + simple inflections).
update texts set word_ids = coalesce((
  select array_agg(w.id) from words w
  where texts.body ~* ('\m' || regexp_replace(w.headword, '([.^$*+?()\[\]{}|\\])', '\\\1', 'g') || '(s|es|ed|d|ing)?\M')
), '{}');
