-- Starter vocabulary (~90 words). Run once after 0001_init.sql, in the
-- Supabase SQL Editor (or `supabase db reset` locally, which runs this
-- automatically). Safe to re-run: conflicting (headword, tag) pairs are skipped.
--
-- This is a small seed set to get the SRS screen working end to end.
-- The plan doc's materials checklist calls for the full Oxford 3000/5000 list
-- and the user's own textbook vocabulary — add those the same way, via more
-- insert statements or a CSV import into `words`.

insert into words (headword, translation, ipa, tag, cefr_level, example_sentence) values
  ('hello', 'привет', '/həˈloʊ/', 'general', 'A1', 'Hello, how are you today?'),
  ('goodbye', 'до свидания', '/ɡʊdˈbaɪ/', 'general', 'A1', 'She waved and said goodbye.'),
  ('please', 'пожалуйста', '/pliːz/', 'general', 'A1', 'Please close the door.'),
  ('thank you', 'спасибо', '/θæŋk juː/', 'general', 'A1', 'Thank you for your help.'),
  ('yes', 'да', '/jɛs/', 'general', 'A1', 'Yes, that is correct.'),
  ('no', 'нет', '/noʊ/', 'general', 'A1', 'No, I do not agree.'),
  ('name', 'имя', '/neɪm/', 'general', 'A1', 'What is your name?'),
  ('day', 'день', '/deɪ/', 'general', 'A1', 'Have a nice day.'),
  ('week', 'неделя', '/wiːk/', 'general', 'A1', 'I work five days a week.'),
  ('month', 'месяц', '/mʌnθ/', 'general', 'A1', 'Next month we start the project.'),
  ('year', 'год', '/jɪr/', 'general', 'A1', 'This year has been busy.'),
  ('time', 'время', '/taɪm/', 'general', 'A1', 'I do not have much time.'),
  ('work', 'работа', '/wɜːrk/', 'general', 'A1', 'I go to work by bus.'),
  ('home', 'дом', '/hoʊm/', 'general', 'A1', 'She stayed home yesterday.'),
  ('friend', 'друг', '/frɛnd/', 'general', 'A1', 'He is my best friend.'),
  ('family', 'семья', '/ˈfæməli/', 'general', 'A1', 'My family lives in another city.'),
  ('food', 'еда', '/fuːd/', 'general', 'A1', 'The food here is very good.'),
  ('water', 'вода', '/ˈwɔːtər/', 'general', 'A1', 'Please give me a glass of water.'),
  ('money', 'деньги', '/ˈmʌni/', 'general', 'A1', 'I do not have much money.'),
  ('help', 'помощь', '/hɛlp/', 'general', 'A1', 'Can you help me, please?'),
  ('question', 'вопрос', '/ˈkwɛstʃən/', 'general', 'A2', 'I have a question about the plan.'),
  ('answer', 'ответ', '/ˈænsər/', 'general', 'A2', 'I do not know the answer.'),
  ('problem', 'проблема', '/ˈprɒbləm/', 'general', 'A2', 'We found a small problem.'),
  ('important', 'важный', '/ɪmˈpɔːrtənt/', 'general', 'A2', 'This meeting is very important.'),
  ('different', 'другой, отличающийся', '/ˈdɪfrənt/', 'general', 'A2', 'That is a different topic.'),
  ('possible', 'возможный', '/ˈpɒsəbəl/', 'general', 'A2', 'Is it possible to finish today?'),
  ('understand', 'понимать', '/ˌʌndərˈstænd/', 'general', 'A2', 'I do not understand this sentence.'),
  ('explain', 'объяснять', '/ɪkˈspleɪn/', 'general', 'A2', 'Can you explain it again?'),
  ('decide', 'решать', '/dɪˈsaɪd/', 'general', 'A2', 'We need to decide soon.'),
  ('change', 'менять', '/tʃeɪndʒ/', 'general', 'A2', 'We changed the plan.'),
  ('start', 'начинать', '/stɑːrt/', 'general', 'A1', 'Let us start the meeting.'),
  ('finish', 'заканчивать', '/ˈfɪnɪʃ/', 'general', 'A1', 'I will finish this later.'),
  ('continue', 'продолжать', '/kənˈtɪnjuː/', 'general', 'A2', 'Please continue with your work.'),
  ('remember', 'помнить', '/rɪˈmɛmbər/', 'general', 'A2', 'I remember that day well.'),
  ('forget', 'забывать', '/fərˈɡɛt/', 'general', 'A2', 'Do not forget your keys.'),
  ('learn', 'учиться', '/lɜːrn/', 'general', 'A1', 'I want to learn English.'),
  ('practice', 'практика; практиковать', '/ˈpræktɪs/', 'general', 'A2', 'Practice makes progress.'),
  ('improve', 'улучшать', '/ɪmˈpruːv/', 'general', 'A2', 'She wants to improve her English.'),
  ('level', 'уровень', '/ˈlɛvəl/', 'general', 'A2', 'My level is still low.'),
  ('speak', 'говорить', '/spiːk/', 'general', 'A1', 'Do you speak English?'),
  ('listen', 'слушать', '/ˈlɪsən/', 'general', 'A1', 'Listen to this song.'),
  ('write', 'писать', '/raɪt/', 'general', 'A1', 'I write in my notebook.'),
  ('read', 'читать', '/riːd/', 'general', 'A1', 'I read books every evening.'),
  ('meeting', 'встреча, совещание', '/ˈmiːtɪŋ/', 'general', 'A2', 'The meeting starts at ten.'),
  ('team', 'команда', '/tiːm/', 'general', 'A2', 'Our team finished the task.'),
  ('project', 'проект', '/ˈprɒdʒɛkt/', 'general', 'A2', 'This project takes three months.'),
  ('deadline', 'дедлайн, крайний срок', '/ˈdɛdlaɪn/', 'general', 'B1', 'The deadline is next Friday.'),
  ('schedule', 'расписание; планировать', '/ˈskɛdʒuːl/', 'general', 'B1', 'Check the schedule for tomorrow.'),
  ('experience', 'опыт', '/ɪkˈspɪriəns/', 'general', 'B1', 'She has five years of experience.'),
  ('progress', 'прогресс', '/ˈprɒɡrɛs/', 'general', 'B1', 'We made good progress today.'),

  ('computer', 'компьютер', '/kəmˈpjuːtər/', 'it', 'A1', 'I work on my computer every day.'),
  ('software', 'программное обеспечение', '/ˈsɒftwɛr/', 'it', 'A2', 'We update the software every month.'),
  ('hardware', 'аппаратное обеспечение', '/ˈhɑːrdwɛr/', 'it', 'A2', 'The hardware needs an upgrade.'),
  ('bug', 'баг, ошибка в коде', '/bʌɡ/', 'it', 'A2', 'There is a bug in this function.'),
  ('fix', 'исправлять', '/fɪks/', 'it', 'A2', 'I fixed the bug yesterday.'),
  ('code', 'код', '/koʊd/', 'it', 'A1', 'This code is easy to read.'),
  ('function', 'функция', '/ˈfʌŋkʃən/', 'it', 'A2', 'This function returns a number.'),
  ('variable', 'переменная', '/ˈvɛriəbəl/', 'it', 'B1', 'The variable stores the user name.'),
  ('database', 'база данных', '/ˈdeɪtəbeɪs/', 'it', 'A2', 'We store users in a database.'),
  ('server', 'сервер', '/ˈsɜːrvər/', 'it', 'A2', 'The server is down right now.'),
  ('client', 'клиент (программа/сторона)', '/ˈklaɪənt/', 'it', 'B1', 'The client sends a request.'),
  ('request', 'запрос', '/rɪˈkwɛst/', 'it', 'A2', 'The request failed with an error.'),
  ('response', 'ответ (сервера)', '/rɪˈspɒns/', 'it', 'A2', 'The response took two seconds.'),
  ('deploy', 'разворачивать (деплоить)', '/dɪˈplɔɪ/', 'it', 'B1', 'We deploy the app every Friday.'),
  ('deployment', 'деплой, развёртывание', '/dɪˈplɔɪmənt/', 'it', 'B1', 'The deployment failed at midnight.'),
  ('release', 'релиз, выпуск', '/rɪˈliːs/', 'it', 'A2', 'The new release is ready.'),
  ('version', 'версия', '/ˈvɜːrʒən/', 'it', 'A2', 'This is the latest version.'),
  ('update', 'обновление; обновлять', '/ʌpˈdeɪt/', 'it', 'A1', 'Please update the app.'),
  ('branch', 'ветка (git)', '/bræntʃ/', 'it', 'B1', 'Create a new branch for this feature.'),
  ('commit', 'коммит; коммитить', '/kəˈmɪt/', 'it', 'B1', 'I made a small commit.'),
  ('merge', 'сливать (ветки)', '/mɜːrdʒ/', 'it', 'B1', 'We need to merge these branches.'),
  ('repository', 'репозиторий', '/rɪˈpɒzɪtɔːri/', 'it', 'B1', 'Clone the repository first.'),
  ('pull request', 'пул-реквест', '/pʊl rɪˈkwɛst/', 'it', 'B1', 'I opened a pull request for review.'),
  ('review', 'обзор, проверка', '/rɪˈvjuː/', 'it', 'A2', 'Can you review my code?'),
  ('test', 'тест; тестировать', '/tɛst/', 'it', 'A1', 'We test the app before release.'),
  ('error', 'ошибка', '/ˈɛrər/', 'it', 'A1', 'The error appeared on the screen.'),
  ('exception', 'исключение (в коде)', '/ɪkˈsɛpʃən/', 'it', 'B1', 'The function throws an exception.'),
  ('debug', 'отлаживать', '/diːˈbʌɡ/', 'it', 'B1', 'I need to debug this issue.'),
  ('issue', 'задача, проблема (в трекере)', '/ˈɪʃuː/', 'it', 'A2', 'I created a new issue.'),
  ('feature', 'функциональность, фича', '/ˈfiːtʃər/', 'it', 'A2', 'This feature is not ready yet.'),
  ('task', 'задача', '/tæsk/', 'it', 'A1', 'I finished my task today.'),
  ('backend', 'бэкенд', '/ˈbækɛnd/', 'it', 'B1', 'The backend handles the data.'),
  ('frontend', 'фронтенд', '/ˈfrʌntɛnd/', 'it', 'B1', 'The frontend shows the interface.'),
  ('api', 'API, интерфейс программирования', '/eɪ piː aɪ/', 'it', 'B1', 'The app uses a public API.'),
  ('endpoint', 'эндпоинт (адрес API)', '/ˈɛndpɔɪnt/', 'it', 'B1', 'This endpoint returns user data.'),
  ('authentication', 'аутентификация', '/ɔːˌθɛntɪˈkeɪʃən/', 'it', 'B2', 'Authentication failed twice.'),
  ('token', 'токен', '/ˈtoʊkən/', 'it', 'B1', 'The token expired an hour ago.'),
  ('cache', 'кэш', '/kæʃ/', 'it', 'B1', 'We cache the results for speed.'),
  ('queue', 'очередь', '/kjuː/', 'it', 'B1', 'The message sits in the queue.'),
  ('standup', 'стендап (короткая встреча команды)', '/ˈstændʌp/', 'it', 'B1', 'Our standup is at nine every day.'),
  ('sprint', 'спринт', '/sprɪnt/', 'it', 'B1', 'This sprint ends on Friday.')
on conflict (lower(headword), tag) do nothing;
