// Builds supabase/seed_words.sql from words.mjs after validating it:
// every book word is either in WORDS or already seeded (supabase/seed.sql),
// no duplicates, required fields present.
//   node supabase/content/build-words.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { BOOK_UNITS, UNITS } from "./words.mjs";

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const seeded = new Set(
  [...readFileSync(new URL("../seed.sql", import.meta.url), "utf8").matchAll(/^\s+\('([^']+)',/gm)].map((m) =>
    m[1].toLowerCase()
  )
);

const errors = [];
if (BOOK_UNITS.length !== UNITS.length) errors.push(`units: book ${BOOK_UNITS.length}, data ${UNITS.length}`);
const seen = new Set();
const rows = [];
UNITS.forEach((unit, u) => {
  const bookWords = BOOK_UNITS[u] ?? [];
  if (bookWords.length !== 20) errors.push(`unit ${u + 1}: book list has ${bookWords.length} words`);
  const given = new Set(unit.book.map((x) => x.headword.toLowerCase()));
  for (const bw of bookWords) {
    if (!given.has(bw) && !seeded.has(bw)) errors.push(`unit ${u + 1}: book word "${bw}" missing`);
    if (given.has(bw) && seeded.has(bw)) errors.push(`unit ${u + 1}: "${bw}" is already seeded — drop it`);
  }
  for (const x of unit.book) if (!bookWords.includes(x.headword)) errors.push(`unit ${u + 1}: "${x.headword}" is not in the book unit`);
  const add = (x, tag, i) => {
    const key = x.headword.toLowerCase();
    if (seen.has(key) || seeded.has(key)) errors.push(`duplicate headword "${x.headword}"`);
    seen.add(key);
    for (const f of ["translation", "ipa", "cefr", "example"]) if (!x[f]) errors.push(`"${x.headword}": missing ${f}`);
    if (!/^\/.+\/$/.test(x.ipa)) errors.push(`"${x.headword}": IPA must be /…/`);
    if (!["A1", "A2", "B1", "B2", "C1"].includes(x.cefr)) errors.push(`"${x.headword}": bad CEFR`);
    // Unit u+1 → 1000 + 100·unit; book words first, then the IT group.
    rows.push({ ...x, tag, source: tag === "it" ? "it-terms" : `nation-4000-1:u${u + 1}`, sort: 1000 + (u + 1) * 100 + i });
  };
  unit.book.forEach((x, i) => add(x, "general", i));
  unit.it.forEach((x, i) => add(x, "it", 50 + i));
});
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

const out = [
  "-- GENERATED by supabase/content/build-words.mjs — edit words.mjs, not this file.",
  "-- Vocabulary textbook units + IT terms in learning order (words.sort_order). Safe to re-run.",
  "",
  "insert into words (headword, translation, ipa, tag, cefr_level, example_sentence, sort_order, source) values",
  rows
    .map((r) => `  (${q(r.headword)}, ${q(r.translation)}, ${q(r.ipa)}, '${r.tag}', '${r.cefr}', ${q(r.example)}, ${r.sort}, ${q(r.source)})`)
    .join(",\n"),
  "on conflict (lower(headword), tag) do update set translation = excluded.translation, ipa = excluded.ipa,",
  "  cefr_level = excluded.cefr_level, example_sentence = excluded.example_sentence,",
  "  sort_order = excluded.sort_order, source = excluded.source;",
  "",
];
writeFileSync(new URL("../seed_words.sql", import.meta.url), out.join("\n"));
const book = rows.filter((r) => r.tag === "general").length;
console.log(`ok: ${book} book words (+${600 - book} already seeded), ${rows.length - book} IT terms`);
