// Builds supabase/seed_phase2.sql from the content modules in this folder and
// validates them first (every gap marked, MC answer among the options, etc.).
//   node supabase/content/build-seed.mjs
import { writeFileSync } from "node:fs";
import { SECTIONS, SUMMARIES } from "./grammar-topics.mjs";
import { EXERCISES } from "./grammar-exercises.mjs";
import { TEXTS } from "./texts.mjs";
import { DIALOGUES, VIDEOS } from "./listening.mjs";

const q = (s) => (s == null ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const arr = (xs) => `array[${xs.map(q).join(", ")}]::text[]`;

const errors = [];
const units = new Set();
for (const [, list] of SECTIONS) for (const [unit] of list) units.add(unit);
for (let u = 1; u <= 115; u++) if (!units.has(u)) errors.push(`unit ${u} missing from SECTIONS`);

for (const [unit, list] of Object.entries(EXERCISES)) {
  if (!units.has(Number(unit))) errors.push(`exercises for unknown unit ${unit}`);
  if (!SUMMARIES[unit]) errors.push(`unit ${unit} has exercises but no summary`);
  list.forEach((ex, i) => {
    const where = `unit ${unit} #${i + 1}`;
    if ((ex.prompt.match(/___/g) ?? []).length !== 1) errors.push(`${where}: needs exactly one ___`);
    if (!ex.why) errors.push(`${where}: missing explanation`);
    if (ex.type === "multiple_choice") {
      if (!ex.options.includes(ex.answer)) errors.push(`${where}: answer not in options`);
      if (new Set(ex.options).size !== ex.options.length) errors.push(`${where}: duplicate options`);
    }
  });
}
TEXTS.forEach((t, i) => {
  if (!["A1", "A2", "B1"].includes(t.level)) errors.push(`text ${i + 1}: bad level`);
  if (t.questions.length < 1) errors.push(`text ${i + 1}: no questions`);
});
DIALOGUES.forEach((d, i) => {
  if (!["A1", "A2", "B1"].includes(d.level)) errors.push(`dialogue ${i + 1}: bad level`);
  if (new Set(d.lines.map((l) => l.speaker)).size < 2) errors.push(`dialogue ${i + 1}: needs two speakers`);
  if (d.lines.some((l) => !l.text.trim())) errors.push(`dialogue ${i + 1}: empty line`);
});
VIDEOS.forEach((v) => {
  if (!/^[\w-]{11}$/.test(v.id)) errors.push(`video "${v.title}": bad YouTube id`);
});
if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

const out = [
  "-- GENERATED by supabase/content/build-seed.mjs — edit the .mjs sources, not this file.",
  "-- Фаза 2 content: grammar topics + exercises, reading texts. Safe to re-run (upserts).",
  "",
  "insert into grammar_topics (unit, section, title, summary) values",
  SECTIONS.flatMap(([section, list]) =>
    list.map(([unit, title]) => `  (${unit}, ${q(section)}, ${q(title)}, ${q(SUMMARIES[unit])})`)
  ).join(",\n"),
  "on conflict (unit) do update set section = excluded.section, title = excluded.title, summary = excluded.summary;",
  "",
];

for (const [unit, list] of Object.entries(EXERCISES)) {
  out.push(
    "insert into grammar_exercises (topic_id, position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)",
    `select t.id, v.position, v.exercise_type::exercise_type, v.prompt, v.options, v.correct_answer, v.accepted_answers, v.explanation`,
    "from (values",
    list.map((ex, i) =>
      `  (${i + 1}, ${q(ex.type)}, ${q(ex.prompt)}, ${ex.options ? arr(ex.options) : "null::text[]"}, ${q(ex.answer)}, ${arr(ex.accept ?? [])}, ${q(ex.why)})`
    ).join(",\n"),
    ") as v(position, exercise_type, prompt, options, correct_answer, accepted_answers, explanation)",
    `join grammar_topics t on t.unit = ${Number(unit)}`,
    "on conflict (topic_id, position) do update set exercise_type = excluded.exercise_type, prompt = excluded.prompt, options = excluded.options, correct_answer = excluded.correct_answer, accepted_answers = excluded.accepted_answers, explanation = excluded.explanation;",
    ""
  );
}

out.push(
  "insert into texts (title, body, cefr_level, position, questions) values",
  TEXTS.map((t, i) =>
    `  (${q(t.title)}, ${q(t.body)}, ${q(t.level)}, ${i + 1}, ${q(JSON.stringify(t.questions))}::jsonb)`
  ).join(",\n"),
  "on conflict (title) do update set body = excluded.body, cefr_level = excluded.cefr_level, position = excluded.position, questions = excluded.questions;",
  "",
  "-- Link each text to the dictionary words it contains (headword + simple inflections).",
  "update texts set word_ids = coalesce((",
  "  select array_agg(w.id) from words w",
  "  where texts.body ~* ('\\m' || regexp_replace(w.headword, '([.^$*+?()\\[\\]{}|\\\\])', '\\\\\\1', 'g') || '(s|es|ed|d|ing)?\\M')",
  "), '{}');",
  ""
);

out.push(
  "-- Listening: own TTS dialogues (exact transcripts) + verified external videos.",
  "insert into listening_items (title, kind, cefr_level, position, lines, transcript, source_url, start_seconds, end_seconds) values",
  [
    ...DIALOGUES.map((d, i) =>
      `  (${q(d.title)}, 'tts', ${q(d.level)}, ${i + 1}, ${q(JSON.stringify(d.lines))}::jsonb, ${q(d.lines.map((l) => `${l.speaker}: ${l.text}`).join("\n"))}, null, 0, null)`
    ),
    ...VIDEOS.map((v, i) =>
      `  (${q(v.title)}, 'youtube', 'B2', ${100 + i}, '[]'::jsonb, null, ${q(`https://www.youtube.com/watch?v=${v.id}`)}, 0, null)`
    ),
  ].join(",\n"),
  "on conflict (title) do update set kind = excluded.kind, cefr_level = excluded.cefr_level, position = excluded.position,",
  "  lines = excluded.lines, transcript = excluded.transcript, source_url = excluded.source_url;",
  ""
);

writeFileSync(new URL("../seed_phase2.sql", import.meta.url), out.join("\n"));
const exCount = Object.values(EXERCISES).reduce((n, l) => n + l.length, 0);
console.log(`ok: ${units.size} topics, ${exCount} exercises, ${TEXTS.length} texts, ${DIALOGUES.length} dialogues, ${VIDEOS.length} videos`);
