// Unit list of the grammar textbook (Murphy, "Essential Grammar in Use", 4th ed.),
// in textbook order. Only the unit titles and order come from the book — the
// summaries and exercises (grammar-exercises.mjs) are written from scratch.
export const SECTIONS = [
  ["Present", [
    [1, "am/is/are"],
    [2, "am/is/are (questions)"],
    [3, "I am doing (present continuous)"],
    [4, "are you doing? (present continuous questions)"],
    [5, "I do/work/like etc. (present simple)"],
    [6, "I don't … (present simple negative)"],
    [7, "Do you …? (present simple questions)"],
    [8, "I am doing (present continuous) and I do (present simple)"],
    [9, "I have … and I've got …"],
  ]],
  ["Past", [
    [10, "was/were"],
    [11, "worked/got/went etc. (past simple)"],
    [12, "I didn't … Did you …? (past simple negative and questions)"],
    [13, "I was doing (past continuous)"],
    [14, "I was doing (past continuous) and I did (past simple)"],
  ]],
  ["Present perfect", [
    [15, "I have done (present perfect 1)"],
    [16, "I've just … I've already … I haven't … yet (present perfect 2)"],
    [17, "Have you ever …? (present perfect 3)"],
    [18, "How long have you …? (present perfect 4)"],
    [19, "for, since, ago"],
    [20, "I have done (present perfect) and I did (past)"],
  ]],
  ["Passive", [
    [21, "is done, was done (passive 1)"],
    [22, "is being done, has been done (passive 2)"],
  ]],
  ["Verb forms", [
    [23, "be/have/do in present and past tenses"],
    [24, "Regular and irregular verbs"],
  ]],
  ["Future", [
    [25, "What are you doing tomorrow?"],
    [26, "I'm going to …"],
    [27, "will/shall 1"],
    [28, "will/shall 2"],
  ]],
  ["Modals, imperative etc.", [
    [29, "might"],
    [30, "can and could"],
    [31, "must, mustn't, don't need to"],
    [32, "should"],
    [33, "I have to …"],
    [34, "Would you like …? I'd like …"],
    [35, "Do this! Don't do that! Let's do this!"],
    [36, "I used to …"],
  ]],
  ["There and it", [
    [37, "there is, there are"],
    [38, "there was/were, there has/have been, there will be"],
    [39, "It …"],
  ]],
  ["Auxiliary verbs", [
    [40, "I am, I don't etc."],
    [41, "Have you? Are you? Don't you? etc."],
    [42, "too/either, so am I / neither do I etc."],
    [43, "isn't, haven't, don't etc. (negatives)"],
  ]],
  ["Questions", [
    [44, "is it …? have you …? do they …? etc. (questions 1)"],
    [45, "Who saw you? Who did you see? (questions 2)"],
    [46, "Who is she talking to? What is it like? (questions 3)"],
    [47, "What …? Which …? How …? (questions 4)"],
    [48, "How long does it take …?"],
    [49, "Do you know where …? I don't know what … etc."],
  ]],
  ["Reported speech", [
    [50, "She said that … He told me that …"],
  ]],
  ["-ing and to …", [
    [51, "work/working, go/going, do/doing"],
    [52, "to … (I want to do) and -ing (I enjoy doing)"],
    [53, "I want you to … I told you to …"],
    [54, "I went to the shop to …"],
  ]],
  ["Go, get, do, make and have", [
    [55, "go to …, go on …, go for …, go -ing"],
    [56, "get"],
    [57, "do and make"],
    [58, "have"],
  ]],
  ["Pronouns and possessives", [
    [59, "I/me, he/him, they/them etc."],
    [60, "my/his/their etc."],
    [61, "Whose is this? It's mine/yours/hers etc."],
    [62, "I/me/my/mine"],
    [63, "myself/yourself/themselves etc."],
    [64, "-'s (Kate's camera / my brother's car etc.)"],
  ]],
  ["A and the", [
    [65, "a/an …"],
    [66, "train(s), bus(es) (singular and plural)"],
    [67, "a bottle / some water (countable/uncountable 1)"],
    [68, "a cake / some cake / some cakes (countable/uncountable 2)"],
    [69, "a/an and the"],
    [70, "the …"],
    [71, "go to work, go home, go to the cinema"],
    [72, "I like music, I hate exams"],
    [73, "the … (names of places)"],
  ]],
  ["Determiners and pronouns", [
    [74, "this/that/these/those"],
    [75, "one/ones"],
    [76, "some and any"],
    [77, "not + any, no, none"],
    [78, "not + anybody/anyone/anything, nobody/no-one/nothing"],
    [79, "somebody/anything/nowhere etc."],
    [80, "every and all"],
    [81, "all, most, some, any, no/none"],
    [82, "both, either, neither"],
    [83, "a lot, much, many"],
    [84, "(a) little, (a) few"],
  ]],
  ["Adjectives and adverbs", [
    [85, "old/nice/interesting etc. (adjectives)"],
    [86, "quickly/badly/suddenly etc. (adverbs)"],
    [87, "old/older, expensive/more expensive"],
    [88, "older than …, more expensive than …"],
    [89, "not as … as"],
    [90, "the oldest, the most expensive"],
    [91, "enough"],
    [92, "too"],
  ]],
  ["Word order", [
    [93, "He speaks English very well. (word order 1)"],
    [94, "always/usually/often etc. (word order 2)"],
    [95, "still, yet, already"],
    [96, "Give me that book! Give it to me!"],
  ]],
  ["Conjunctions and clauses", [
    [97, "and, but, or, so, because"],
    [98, "When …"],
    [99, "If we go … If you see … etc."],
    [100, "If I had … If we went … etc."],
    [101, "a person who … a thing that/which … (relative clauses 1)"],
    [102, "the people we met, the hotel you stayed at (relative clauses 2)"],
  ]],
  ["Prepositions", [
    [103, "at 8 o'clock, on Monday, in April"],
    [104, "from … to, until, since, for"],
    [105, "before, after, during, while"],
    [106, "in, at, on (places 1)"],
    [107, "in, at, on (places 2)"],
    [108, "to, in, at (places 3)"],
    [109, "under, behind, opposite etc."],
    [110, "up, over, through etc."],
    [111, "on, at, by, with, about"],
    [112, "afraid of …, good at … etc.; of/at/for etc. (prepositions) + -ing"],
    [113, "listen to …, look at … etc. (verb + preposition)"],
  ]],
  ["Phrasal verbs", [
    [114, "go in, fall off, run away etc. (phrasal verbs 1)"],
    [115, "put on your shoes, put your shoes on (phrasal verbs 2)"],
  ]],
];

// Rule summaries in Russian, own wording. Only units that have exercises need one.
export const SUMMARIES = {
  1: "Глагол to be в настоящем времени: I am; he/she/it is; we/you/they are. Краткие формы: I'm, he's, it's, we're, they're. Отрицание — добавляем not: I'm not, he isn't, they aren't.",
  2: "В вопросе am/is/are встаёт перед подлежащим: Am I…? Is it…? Are you…? Вопросительное слово — в самом начале: Where is…? Короткие ответы: Yes, I am. / No, it isn't. В утвердительном коротком ответе сокращать нельзя: Yes, I am (не Yes, I'm).",
  3: "Present continuous = am/is/are + глагол с -ing. Так говорят о том, что происходит сейчас, в момент речи: I'm working. She isn't listening. Орфография: write → writing (немая e выпадает), run → running (согласная удваивается), lie → lying.",
  4: "Вопрос в present continuous: am/is/are ставим перед подлежащим, затем глагол с -ing: Are you working? What is she doing? Where are they going? Короткие ответы: Yes, I am. / No, he isn't.",
  5: "Present simple: I/you/we/they work, но he/she/it works — в 3-м лице единственного числа добавляем -s. Время для того, что бывает регулярно, всегда или вообще верно: I work in IT. The office opens at nine. Орфография: после s, sh, ch, x, o пишем -es (watches, goes, does); согласная + y → -ies (study → studies); have → has.",
  6: "Отрицание в present simple: I/you/we/they don't + глагол; he/she/it doesn't + глагол. После doesn't глагол без -s: She doesn't work (не doesn't works). don't = do not, doesn't = does not.",
  7: "Вопрос в present simple: Do + I/you/we/they + глагол? Does + he/she/it + глагол? После does глагол без -s: Does she work…? Вопросительное слово — в начале: Where do you live? What does it mean? Короткие ответы: Yes, I do. / No, she doesn't.",
  8: "Present continuous (am/is/are + -ing) — то, что происходит сейчас или в эти дни: I'm fixing a bug right now. Present simple — привычки, регулярные действия, факты: I fix bugs every day. Глаголы know, like, want, need, understand, mean, prefer, believe, remember обычно не ставят в continuous: I know (не I'm knowing).",
  9: "Have и have got значат одно и то же — «иметь»: I have a laptop = I've got a laptop; he/she/it has = has got. Отрицание: I don't have = I haven't got. Вопрос: Do you have…? = Have you got…? Не смешивай формы: Do you have… (не Have you have…). В прошедшем времени только had: I had a cold last week.",
  10: "Прошедшее время глагола to be: I/he/she/it was; we/you/they were. Отрицание: wasn't, weren't. Вопрос: Was she…? Were you…? Короткие ответы: Yes, I was. / No, they weren't.",
  11: "Past simple — законченное действие в прошлом: I worked yesterday. Правильные глаголы получают -ed: work → worked, live → lived, stop → stopped, study → studied. Неправильные надо запомнить: go → went, get → got, have → had, see → saw, make → made, find → found, send → sent, write → wrote. Форма одна для всех лиц: I/he/they worked.",
  12: "Отрицание в past simple: didn't + глагол в начальной форме, для всех лиц: I didn't go (не didn't went). Вопрос: Did + подлежащее + глагол: Did you see it? What did she say? Короткие ответы: Yes, I did. / No, they didn't.",
};
