// Vocabulary in learning order. BOOK_UNITS lists the target words of the
// vocabulary textbook (Nation, "4000 Essential English Words 1") exactly as the
// book groups them; WORDS gives each one our own translation, IPA (General
// American), CEFR estimate and example sentence — the book's definitions and
// examples are not copied. Meanings follow the sense the book teaches.
// After each book unit comes a group of IT terms (`it`), so the queue mixes
// general words with industry vocabulary. Book words already in seed.sql are
// skipped automatically (build-seed.mjs checks that every book word is covered).

export const BOOK_UNITS = [
  "afraid agree angry arrive attack bottom clever cruel finally hide hunt lot middle moment pleased promise reply safe trick well",
  "adventure approach carefully chemical create evil experiment kill laboratory laugh loud nervous noise project scare secret shout smell terrible worse",
  "alien among chart cloud comprehend describe ever fail friendly grade instead library planet report several solve suddenly suppose universe view",
  "appropriate avoid behave calm concern content expect frequently habit instruct issue none patient positive punish represent shake spread stroll village",
  "aware badly belong continue error experience field hurt judgment likely normal rare relax request reside result roll since visible wild",
  "advantage cause choice community dead distance escape face follow fright ghost individual pet reach return survive upset voice weather wise",
  "allow announce beside challenge claim condition contribute difference divide expert famous force harm lay peace prince protect sense sudden therefore",
  "accept arrange attend balance contrast encourage familiar grab hang huge necessary pattern propose purpose release require single success tear theory",
  "against beach damage discover emotion fix frank identify island ocean perhaps pleasant prevent rock save step still taste throw wave",
  "benefit certain chance effect essential far focus function grass guard image immediate primary proud remain rest separate site tail trouble",
  "anymore asleep berry collect compete conversation creature decision either forest ground introduce marry prepare sail serious spend strange truth wake",
  "alone apartment article artist attitude compare judge magazine material meal method neighbor professional profit quality shape space stair symbol thin",
  "blood burn cell contain correct crop demand equal feed hole increase lord owe position raise responsible sight spot structure whole",
  "coach control description direct exam example limit local magical mail novel outline poet print scene sheet silly store suffer technology",
  "across breathe characteristic consume excite extreme fear fortunate happen length mistake observe opportunity prize race realize respond risk wonder yet",
  "academy ancient board century clue concert county dictionary exist flat gentleman hidden maybe officer original pound process publish theater wealth",
  "appreciate available beat bright celebrate determine disappear else fair flow forward hill level lone puddle response season solution waste whether",
  "argue communicate crowd depend dish empty exact fresh gather indicate item offer price product property purchase recommend select tool treat",
  "alive bone bother captain conclusion doubt explore foreign glad however injustice international lawyer mention policy social speech staff toward wood",
  "achieve advise already basic bit consider destroy entertain extra goal lie meat opinion real reflect regard serve vegetable war worth",
  "appear base brain career clerk effort enter excellent hero hurry inform later leave locate nurse operation pain refuse though various",
  "actual amaze charge comfort contact customer deliver earn gate include manage mystery occur opposite plate receive reward set steal thief",
  "advance athlete average behavior behind course lower match member mental passenger personality poem pole remove safety shoot sound swim web",
  "block cheer complex critic event exercise fit friendship guide lack passage perform pressure probable public strike support task term unite",
  "associate environment factory feature instance involve medicine mix organize period populate produce range recognize regular sign tip tradition trash wide",
  "advice along attention attract climb drop final further imply maintain neither otherwise physical prove react ride situated society standard suggest",
  "actually bite coast deal desert earthquake effective examine false gift hunger imagine journey puzzle quite rather specific tour trip value",
  "band barely boring cancel driveway garbage instrument list magic message notice own predict professor rush schedule share stage storm within",
  "advertise assign audience breakfast competition cool gain importance knowledge major mean prefer president progress respect rich skill somehow strength vote",
  "above ahead amount belief center common cost demonstrate different evidence honesty idiom independent inside master memory proper scan section surface",
].map((line) => line.split(" "));

// [headword, translation, ipa, cefr, example]
const w = (headword, translation, ipa, cefr, example) => ({ headword, translation, ipa, cefr, example });

export const UNITS = [
  {
    book: [
      w("afraid", "боящийся, испуганный", "/əˈfreɪd/", "A1", "Don't be afraid to ask questions in the meeting."),
      w("agree", "соглашаться", "/əˈɡriː/", "A1", "I agree with your idea."),
      w("angry", "злой, сердитый", "/ˈæŋɡri/", "A1", "The client was angry because the site was down."),
      w("arrive", "прибывать, приходить", "/əˈraɪv/", "A1", "I usually arrive at the office at nine."),
      w("attack", "атаковать, нападать; атака", "/əˈtæk/", "B1", "Hackers attacked the server last night."),
      w("bottom", "низ, дно", "/ˈbɑːtəm/", "A2", "The button is at the bottom of the page."),
      w("clever", "умный, сообразительный", "/ˈklɛvər/", "A2", "That is a clever solution."),
      w("cruel", "жестокий", "/ˈkruːəl/", "B1", "It was cruel to laugh at his mistake."),
      w("finally", "наконец", "/ˈfaɪnəli/", "A2", "We finally found the bug."),
      w("hide", "прятать(ся), скрывать", "/haɪd/", "A2", "The menu hides on small screens."),
      w("hunt", "охотиться; искать", "/hʌnt/", "B1", "We spent the whole day hunting for the bug."),
      w("lot", "много (a lot of)", "/lɑːt/", "A1", "I have a lot of work today."),
      w("middle", "середина", "/ˈmɪdəl/", "A1", "Put the logo in the middle of the page."),
      w("moment", "момент, миг", "/ˈmoʊmənt/", "A1", "Wait a moment, please."),
      w("pleased", "довольный", "/pliːzd/", "A2", "The team was pleased with the release."),
      w("promise", "обещать; обещание", "/ˈprɑːmɪs/", "A2", "I promise to finish it by Friday."),
      w("reply", "отвечать; ответ", "/rɪˈplaɪ/", "A2", "Please reply to my email."),
      w("safe", "безопасный", "/seɪf/", "A2", "Keep your password in a safe place."),
      w("trick", "трюк, уловка", "/trɪk/", "B1", "Here is a useful trick for Git."),
      w("well", "хорошо", "/wɛl/", "A1", "She speaks English very well."),
    ],
    it: [
      w("laptop", "ноутбук", "/ˈlæptɑːp/", "A2", "I work on a laptop at home."),
      w("keyboard", "клавиатура", "/ˈkiːbɔːrd/", "A2", "My new keyboard is very quiet."),
      w("screen", "экран", "/skriːn/", "A2", "Can you share your screen?"),
      w("file", "файл", "/faɪl/", "A2", "Save the file before you close it."),
      w("folder", "папка", "/ˈfoʊldər/", "A2", "All the images are in this folder."),
    ],
  },
  {
    book: [
      w("adventure", "приключение", "/ədˈvɛntʃər/", "A2", "Starting a new job is an adventure."),
      w("approach", "подход; приближаться", "/əˈproʊtʃ/", "B1", "Let's try a different approach."),
      w("carefully", "внимательно, осторожно", "/ˈkɛrfəli/", "A2", "Read the error message carefully."),
      w("chemical", "химический; химикат", "/ˈkɛmɪkəl/", "B1", "This chemical is dangerous."),
      w("create", "создавать", "/kriˈeɪt/", "A2", "Create a new branch for this task."),
      w("evil", "злой; зло", "/ˈiːvəl/", "B1", "The film is about an evil robot."),
      w("experiment", "эксперимент", "/ɪkˈspɛrɪmənt/", "A2", "We ran an experiment with a new design."),
      w("kill", "убивать; завершать (процесс)", "/kɪl/", "A2", "Kill the process and start it again."),
      w("laboratory", "лаборатория", "/ˈlæbrətɔːri/", "B1", "She works in a science laboratory."),
      w("laugh", "смеяться", "/læf/", "A2", "Everybody laughed at his joke."),
      w("loud", "громкий", "/laʊd/", "A2", "The music in the office is too loud."),
      w("nervous", "нервный, взволнованный", "/ˈnɜːrvəs/", "A2", "I am nervous before interviews."),
      w("noise", "шум", "/nɔɪz/", "A2", "The noise from the street is terrible."),
      w("scare", "пугать", "/skɛr/", "B1", "Big deadlines scare me."),
      w("secret", "секрет; секретный", "/ˈsiːkrət/", "A2", "Never share your secret key."),
      w("shout", "кричать", "/ʃaʊt/", "A2", "Please don't shout in the office."),
      w("smell", "запах; пахнуть", "/smɛl/", "A2", "I love the smell of coffee."),
      w("terrible", "ужасный", "/ˈtɛrəbəl/", "A2", "The Wi-Fi here is terrible."),
      w("worse", "хуже", "/wɜːrs/", "A2", "The new version is worse than the old one."),
    ],
    it: [
      w("password", "пароль", "/ˈpæswɜːrd/", "A2", "Change your password every few months."),
      w("email", "электронная почта; письмо", "/ˈiːmeɪl/", "A1", "I sent you an email this morning."),
      w("link", "ссылка", "/lɪŋk/", "A2", "Click the link to open the page."),
      w("browser", "браузер", "/ˈbraʊzər/", "B1", "Which browser do you use?"),
      w("website", "веб-сайт", "/ˈwɛbsaɪt/", "A2", "Our website is very fast."),
    ],
  },
  {
    book: [
      w("alien", "инопланетянин; чужой", "/ˈeɪliən/", "B2", "The film is about an alien on Earth."),
      w("among", "среди", "/əˈmʌŋ/", "A2", "She is the best among our testers."),
      w("chart", "диаграмма, график", "/tʃɑːrt/", "B1", "This chart shows our users by month."),
      w("cloud", "облако; облачное хранилище", "/klaʊd/", "A2", "We keep our files in the cloud."),
      w("comprehend", "понимать, постигать", "/ˌkɑːmprɪˈhɛnd/", "B2", "I can't comprehend this old code."),
      w("describe", "описывать", "/dɪˈskraɪb/", "A2", "Describe the bug in the ticket."),
      w("ever", "когда-либо", "/ˈɛvər/", "A2", "Have you ever used Docker?"),
      w("fail", "терпеть неудачу; падать (о тесте)", "/feɪl/", "A2", "Two tests failed after my change."),
      w("friendly", "дружелюбный", "/ˈfrɛndli/", "A1", "Our new team lead is very friendly."),
      w("grade", "оценка", "/ɡreɪd/", "A2", "He got a good grade in math."),
      w("instead", "вместо (этого)", "/ɪnˈstɛd/", "A2", "Use a function instead of copying code."),
      w("library", "библиотека", "/ˈlaɪbrɛri/", "A1", "We use a library to work with dates."),
      w("planet", "планета", "/ˈplænɪt/", "A2", "Mars is a red planet."),
      w("report", "отчёт; сообщать", "/rɪˈpɔːrt/", "A2", "Please report the bug to the team."),
      w("several", "несколько", "/ˈsɛvrəl/", "A2", "I tried several times."),
      w("solve", "решать", "/sɑːlv/", "A2", "We solved the problem in one hour."),
      w("suddenly", "внезапно", "/ˈsʌdənli/", "A2", "Suddenly, the server stopped."),
      w("suppose", "предполагать", "/səˈpoʊz/", "B1", "I suppose he is right."),
      w("universe", "вселенная", "/ˈjuːnɪvɜːrs/", "B1", "Our universe is very old."),
      w("view", "смотреть; вид", "/vjuː/", "A2", "You can view the logs here."),
    ],
    it: [
      w("app", "приложение", "/æp/", "A2", "Download our app on your phone."),
      w("click", "нажимать, кликать", "/klɪk/", "A2", "Click the green button."),
      w("download", "скачивать", "/ˌdaʊnˈloʊd/", "A2", "Download the file and open it."),
      w("install", "устанавливать", "/ɪnˈstɔːl/", "B1", "Install Node before you start."),
      w("user", "пользователь", "/ˈjuːzər/", "A2", "The user can't log in."),
    ],
  },
  {
    book: [
      w("appropriate", "подходящий, уместный", "/əˈproʊpriət/", "B1", "Choose an appropriate name for the variable."),
      w("avoid", "избегать", "/əˈvɔɪd/", "B1", "Avoid long functions."),
      w("behave", "вести себя", "/bɪˈheɪv/", "B1", "The app behaves strangely on old phones."),
      w("calm", "спокойный", "/kɑːm/", "B1", "Stay calm when production is down."),
      w("concern", "беспокойство, забота", "/kənˈsɜːrn/", "B1", "Security is our main concern."),
      w("content", "довольный", "/kənˈtɛnt/", "B2", "He is content with his salary."),
      w("expect", "ожидать", "/ɪkˈspɛkt/", "A2", "I expect an answer tomorrow."),
      w("frequently", "часто", "/ˈfriːkwəntli/", "B1", "We deploy frequently."),
      w("habit", "привычка", "/ˈhæbɪt/", "A2", "Writing tests is a good habit."),
      w("instruct", "инструктировать, обучать", "/ɪnˈstrʌkt/", "B2", "She instructs new developers."),
      w("none", "ни один, никто", "/nʌn/", "A2", "None of the tests failed."),
      w("patient", "терпеливый", "/ˈpeɪʃənt/", "B1", "Be patient with new users."),
      w("positive", "положительный", "/ˈpɑːzətɪv/", "A2", "We got positive feedback."),
      w("punish", "наказывать", "/ˈpʌnɪʃ/", "B1", "Nobody punishes you for a bug."),
      w("represent", "представлять (интересы)", "/ˌrɛprɪˈzɛnt/", "B1", "She represents our team at the meeting."),
      w("shake", "трясти", "/ʃeɪk/", "A2", "Shake the phone to report a bug."),
      w("spread", "распространять(ся)", "/sprɛd/", "B1", "The news spread quickly."),
      w("stroll", "прогуливаться", "/stroʊl/", "B2", "We strolled in the park after lunch."),
      w("village", "деревня", "/ˈvɪlɪdʒ/", "A2", "My grandparents live in a small village."),
    ],
    it: [
      w("data", "данные", "/ˈdeɪtə/", "A2", "We store user data in the database."),
      w("internet", "интернет", "/ˈɪntərnɛt/", "A1", "The internet is slow today."),
      w("network", "сеть", "/ˈnɛtwɜːrk/", "B1", "Check your network connection."),
      w("account", "аккаунт, учётная запись", "/əˈkaʊnt/", "A2", "Create an account to continue."),
      w("login", "вход (в систему); логин", "/ˈlɔːɡɪn/", "B1", "The login page is broken."),
    ],
  },
  {
    book: [
      w("aware", "осведомлённый (be aware of — знать о)", "/əˈwɛr/", "B1", "Are you aware of this problem?"),
      w("badly", "плохо", "/ˈbædli/", "A2", "The app works badly offline."),
      w("belong", "принадлежать", "/bɪˈlɔːŋ/", "A2", "This laptop belongs to the company."),
      w("field", "поле; область, сфера", "/fiːld/", "A2", "Fill in every field of the form."),
      w("hurt", "причинять боль; болеть", "/hɜːrt/", "A2", "My eyes hurt after a long day."),
      w("judgment", "суждение, мнение", "/ˈdʒʌdʒmənt/", "B2", "Use your own judgment."),
      w("likely", "вероятный; вероятно", "/ˈlaɪkli/", "B1", "It is likely a network problem."),
      w("normal", "нормальный, обычный", "/ˈnɔːrməl/", "A2", "Is this behavior normal?"),
      w("rare", "редкий", "/rɛr/", "B1", "This bug is rare."),
      w("relax", "расслабляться", "/rɪˈlæks/", "A2", "Relax, it's only a test server."),
      w("reside", "проживать", "/rɪˈzaɪd/", "C1", "She resides in Berlin."),
      w("result", "результат", "/rɪˈzʌlt/", "A2", "Check the result of the query."),
      w("roll", "катить(ся)", "/roʊl/", "B1", "The ball rolled under the desk."),
      w("since", "с (какого-то времени); так как", "/sɪns/", "A2", "I have worked here since 2020."),
      w("visible", "видимый", "/ˈvɪzəbəl/", "B1", "The button is not visible on mobile."),
      w("wild", "дикий", "/waɪld/", "A2", "Wild animals live in the forest."),
    ],
    it: [
      w("developer", "разработчик", "/dɪˈvɛləpər/", "B1", "She is a senior developer."),
      w("programmer", "программист", "/ˈproʊɡræmər/", "A2", "My brother is a programmer."),
      w("tester", "тестировщик", "/ˈtɛstər/", "B1", "The tester found three bugs."),
      w("designer", "дизайнер", "/dɪˈzaɪnər/", "A2", "The designer made a new logo."),
      w("manager", "менеджер, руководитель", "/ˈmænɪdʒər/", "A2", "Ask the project manager."),
    ],
  },
  {
    book: [
      w("advantage", "преимущество", "/ədˈvæntɪdʒ/", "B1", "Speed is the main advantage of this tool."),
      w("cause", "причина; вызывать", "/kɔːz/", "B1", "What caused the error?"),
      w("choice", "выбор", "/tʃɔɪs/", "A2", "We had no choice."),
      w("community", "сообщество", "/kəˈmjuːnəti/", "B1", "The Python community is very large."),
      w("dead", "мёртвый; разряженный", "/dɛd/", "A2", "My phone is dead."),
      w("distance", "расстояние", "/ˈdɪstəns/", "A2", "The distance between the two cities is 300 km."),
      w("escape", "убегать, сбегать", "/ɪˈskeɪp/", "B1", "The cat escaped through the window."),
      w("face", "сталкиваться (с проблемой); лицо", "/feɪs/", "A2", "We face this problem every week."),
      w("follow", "следовать", "/ˈfɑːloʊ/", "A2", "Follow the steps in the README."),
      w("fright", "испуг", "/fraɪt/", "B2", "The loud noise gave me a fright."),
      w("ghost", "призрак", "/ɡoʊst/", "B1", "Do you believe in ghosts?"),
      w("individual", "отдельный; человек", "/ˌɪndɪˈvɪdʒuəl/", "B1", "Each individual test must pass."),
      w("pet", "домашнее животное", "/pɛt/", "A2", "Do you have a pet?"),
      w("reach", "достигать, дотягиваться", "/riːtʃ/", "B1", "We reached ten thousand users."),
      w("return", "возвращать(ся)", "/rɪˈtɜːrn/", "A2", "The function returns a number."),
      w("survive", "выживать", "/sərˈvaɪv/", "B1", "Our startup survived its first year."),
      w("upset", "расстроенный", "/ʌpˈsɛt/", "B1", "She was upset about the bad review."),
      w("voice", "голос", "/vɔɪs/", "A2", "I can't hear your voice — you are on mute."),
      w("weather", "погода", "/ˈwɛðər/", "A1", "The weather is nice today."),
      w("wise", "мудрый", "/waɪz/", "B1", "It is wise to make a backup first."),
    ],
    it: [
      w("program", "программа", "/ˈproʊɡræm/", "A2", "This program converts images."),
      w("script", "скрипт", "/skrɪpt/", "B1", "Run the script to build the project."),
      w("command", "команда", "/kəˈmænd/", "B1", "Type this command in the terminal."),
      w("terminal", "терминал", "/ˈtɜːrmɪnəl/", "B2", "Open a terminal and run the tests."),
      w("output", "вывод, результат (программы)", "/ˈaʊtpʊt/", "B1", "The output of the script is empty."),
    ],
  },
  {
    book: [
      w("allow", "разрешать", "/əˈlaʊ/", "A2", "The app doesn't allow empty passwords."),
      w("announce", "объявлять", "/əˈnaʊns/", "B1", "They announced the new version today."),
      w("beside", "рядом с", "/bɪˈsaɪd/", "A2", "My desk is beside the window."),
      w("challenge", "вызов, сложная задача", "/ˈtʃælɪndʒ/", "B1", "This project is a real challenge."),
      w("claim", "утверждать", "/kleɪm/", "B1", "He claims the bug is fixed."),
      w("condition", "условие; состояние", "/kənˈdɪʃən/", "B1", "Check the condition in the if statement."),
      w("contribute", "вносить вклад", "/kənˈtrɪbjuːt/", "B1", "Everyone can contribute to open source."),
      w("difference", "разница", "/ˈdɪfrəns/", "A2", "What's the difference between these two versions?"),
      w("divide", "делить", "/dɪˈvaɪd/", "A2", "Divide the task into small steps."),
      w("expert", "эксперт", "/ˈɛkspɜːrt/", "A2", "She is an expert in security."),
      w("famous", "знаменитый", "/ˈfeɪməs/", "A2", "Linux is a famous open-source project."),
      w("force", "сила; заставлять", "/fɔːrs/", "B1", "Don't force people to work at night."),
      w("harm", "вред; вредить", "/hɑːrm/", "B1", "One small bug can do a lot of harm."),
      w("lay", "класть, положить", "/leɪ/", "B1", "Lay the papers on my desk."),
      w("peace", "мир, покой", "/piːs/", "A2", "I need some peace to focus."),
      w("prince", "принц", "/prɪns/", "A2", "The prince lived in a big castle."),
      w("protect", "защищать", "/prəˈtɛkt/", "A2", "A strong password protects your account."),
      w("sense", "чувство; смысл", "/sɛns/", "B1", "This code doesn't make sense."),
      w("sudden", "внезапный", "/ˈsʌdən/", "B1", "There was a sudden drop in traffic."),
      w("therefore", "поэтому, следовательно", "/ˈðɛrfɔːr/", "B1", "The data is old; therefore, the result is wrong."),
    ],
    it: [
      w("input", "ввод, входные данные", "/ˈɪnpʊt/", "B1", "Always check user input."),
      w("string", "строка", "/strɪŋ/", "B1", "The name is stored as a string."),
      w("integer", "целое число", "/ˈɪntɪdʒər/", "B2", "The age must be an integer."),
      w("boolean", "булево значение (true/false)", "/ˈbuːliən/", "B2", "This function returns a boolean."),
      w("array", "массив", "/əˈreɪ/", "B2", "Sort the array before you search it."),
    ],
  },
  {
    book: [
      w("accept", "принимать", "/əkˈsɛpt/", "A2", "The API accepts only JSON."),
      w("arrange", "организовывать, договариваться", "/əˈreɪndʒ/", "A2", "Let's arrange a call for Monday."),
      w("attend", "посещать, присутствовать", "/əˈtɛnd/", "B1", "I can't attend the meeting today."),
      w("balance", "удерживать равновесие; баланс", "/ˈbæləns/", "B1", "It is hard to balance work and study."),
      w("contrast", "контраст", "/ˈkɑːntræst/", "B1", "The text needs more contrast."),
      w("encourage", "поощрять, вдохновлять", "/ɪnˈkɜːrɪdʒ/", "B1", "Our lead encourages us to ask questions."),
      w("familiar", "знакомый", "/fəˈmɪljər/", "B1", "Are you familiar with React?"),
      w("grab", "хватать", "/ɡræb/", "B1", "Let's grab a coffee."),
      w("hang", "вешать; висеть; зависать", "/hæŋ/", "B1", "The app hangs when I open this page."),
      w("huge", "огромный", "/hjuːdʒ/", "A2", "The log file is huge."),
      w("necessary", "необходимый", "/ˈnɛsəsɛri/", "A2", "Is this step really necessary?"),
      w("pattern", "шаблон, закономерность", "/ˈpætərn/", "B1", "Do you see a pattern in these errors?"),
      w("propose", "предлагать", "/prəˈpoʊz/", "B1", "I propose a simpler solution."),
      w("purpose", "цель, назначение", "/ˈpɜːrpəs/", "B1", "What is the purpose of this function?"),
      w("require", "требовать", "/rɪˈkwaɪər/", "B1", "This task requires more time."),
      w("single", "единственный, одиночный", "/ˈsɪŋɡəl/", "A2", "One single line broke the build."),
      w("success", "успех", "/səkˈsɛs/", "A2", "The launch was a big success."),
      w("tear", "рвать", "/tɛr/", "B1", "Don't tear the paper."),
      w("theory", "теория", "/ˈθiːəri/", "B1", "In theory, it should work."),
    ],
    it: [
      w("object", "объект", "/ˈɑːbdʒɛkt/", "B1", "Create an object for each user."),
      w("class", "класс", "/klæs/", "A2", "The User class has three methods."),
      w("loop", "цикл", "/luːp/", "B1", "The loop runs ten times."),
      w("parameter", "параметр", "/pəˈræmɪtər/", "B2", "This function takes two parameters."),
      w("argument", "аргумент; спор", "/ˈɑːrɡjəmənt/", "B1", "Pass the file name as an argument."),
    ],
  },
  {
    book: [
      w("against", "против", "/əˈɡɛnst/", "A2", "I am against this change."),
      w("beach", "пляж", "/biːtʃ/", "A1", "We went to the beach on Sunday."),
      w("damage", "ущерб; повреждать", "/ˈdæmɪdʒ/", "B1", "The bug did not damage any data."),
      w("discover", "обнаруживать", "/dɪˈskʌvər/", "A2", "We discovered the problem last week."),
      w("emotion", "эмоция", "/ɪˈmoʊʃən/", "B1", "Try to keep emotion out of code reviews."),
      w("frank", "откровенный", "/fræŋk/", "B2", "Let me be frank: the design is bad."),
      w("identify", "определять, выявлять", "/aɪˈdɛntɪfaɪ/", "B1", "We identified the cause of the crash."),
      w("island", "остров", "/ˈaɪlənd/", "A2", "They live on a small island."),
      w("ocean", "океан", "/ˈoʊʃən/", "A2", "The ocean is cold here."),
      w("perhaps", "возможно", "/pərˈhæps/", "A2", "Perhaps the cache is old."),
      w("pleasant", "приятный", "/ˈplɛzənt/", "B1", "It was a pleasant meeting."),
      w("prevent", "предотвращать", "/prɪˈvɛnt/", "B1", "Tests prevent many bugs."),
      w("rock", "камень, скала", "/rɑːk/", "A2", "They climbed the big rock."),
      w("save", "сохранять; спасать", "/seɪv/", "A2", "Don't forget to save your work."),
      w("step", "шаг; шагать", "/stɛp/", "A2", "Follow these steps."),
      w("still", "всё ещё", "/stɪl/", "A2", "The bug is still there."),
      w("taste", "вкус; пробовать на вкус", "/teɪst/", "A2", "This coffee has a strange taste."),
      w("throw", "бросать; выбрасывать (исключение)", "/θroʊ/", "A2", "The function throws an error."),
      w("wave", "волна; махать", "/weɪv/", "A2", "The wave was very high."),
    ],
    it: [
      w("framework", "фреймворк", "/ˈfreɪmwɜːrk/", "B2", "Next.js is a React framework."),
      w("package", "пакет", "/ˈpækɪdʒ/", "A2", "Install this package with npm."),
      w("dependency", "зависимость", "/dɪˈpɛndənsi/", "C1", "Update the dependencies every month."),
      w("module", "модуль", "/ˈmɑːdʒuːl/", "B2", "Move this code to a separate module."),
      w("import", "импортировать", "/ɪmˈpɔːrt/", "B1", "Import the function at the top of the file."),
    ],
  },
  {
    book: [
      w("benefit", "польза, выгода", "/ˈbɛnɪfɪt/", "B1", "What is the benefit of this change?"),
      w("certain", "уверенный; определённый", "/ˈsɜːrtən/", "B1", "Are you certain it works?"),
      w("chance", "шанс, возможность", "/tʃæns/", "A2", "Give me a chance to explain."),
      w("effect", "эффект, влияние", "/ɪˈfɛkt/", "B1", "The change had no effect on speed."),
      w("essential", "необходимый, важнейший", "/ɪˈsɛnʃəl/", "B1", "Tests are essential."),
      w("far", "далеко; далёкий", "/fɑːr/", "A1", "The office is not far from my home."),
      w("focus", "сосредотачиваться; фокус", "/ˈfoʊkəs/", "B1", "I need to focus on this task."),
      w("grass", "трава", "/ɡræs/", "A2", "Keep off the grass."),
      w("guard", "охранять; охранник", "/ɡɑːrd/", "B1", "A guard stands at the door."),
      w("image", "изображение", "/ˈɪmɪdʒ/", "B1", "The image is too big."),
      w("immediate", "немедленный", "/ɪˈmiːdiət/", "B1", "This bug needs an immediate fix."),
      w("primary", "главный, основной", "/ˈpraɪmɛri/", "B1", "Our primary goal is speed."),
      w("proud", "гордый", "/praʊd/", "A2", "I am proud of our team."),
      w("remain", "оставаться", "/rɪˈmeɪn/", "B1", "Two tasks remain."),
      w("rest", "отдых; остальное", "/rɛst/", "A2", "Take a rest after the release."),
      w("separate", "отдельный; разделять", "/ˈsɛpərət/", "B1", "Keep the tests in a separate folder."),
      w("site", "место; сайт", "/saɪt/", "B1", "The site is down again."),
      w("tail", "хвост", "/teɪl/", "A2", "The dog wagged its tail."),
      w("trouble", "проблема, неприятность", "/ˈtrʌbəl/", "A2", "I have trouble with my laptop."),
    ],
    it: [
      w("build", "сборка; собирать", "/bɪld/", "A2", "The build takes five minutes."),
      w("compile", "компилировать", "/kəmˈpaɪl/", "C1", "The code doesn't compile."),
      w("runtime", "время выполнения; среда выполнения", "/ˈrʌntaɪm/", "C1", "This error happens at runtime."),
      w("crash", "падение, сбой; падать", "/kræʃ/", "B1", "The app crashes on start."),
      w("freeze", "зависать; замораживать", "/friːz/", "B1", "My computer froze again."),
    ],
  },
  {
    book: [
      w("anymore", "больше не (not … anymore)", "/ˌɛniˈmɔːr/", "B1", "We don't use this library anymore."),
      w("asleep", "спящий", "/əˈsliːp/", "A2", "The baby is asleep."),
      w("berry", "ягода", "/ˈbɛri/", "B1", "I eat berries for breakfast."),
      w("collect", "собирать", "/kəˈlɛkt/", "A2", "The app collects data about errors."),
      w("compete", "соревноваться, конкурировать", "/kəmˈpiːt/", "B1", "We compete with big companies."),
      w("conversation", "разговор", "/ˌkɑːnvərˈseɪʃən/", "A2", "We had a long conversation about the design."),
      w("creature", "существо", "/ˈkriːtʃər/", "B1", "Strange creatures live in the ocean."),
      w("decision", "решение", "/dɪˈsɪʒən/", "B1", "It was a hard decision."),
      w("either", "любой (из двух); тоже (в отрицании)", "/ˈiːðər/", "B1", "You can use either Python or Go."),
      w("forest", "лес", "/ˈfɔːrɪst/", "A2", "We walked in the forest."),
      w("ground", "земля", "/ɡraʊnd/", "A2", "The phone fell on the ground."),
      w("introduce", "представлять (знакомить); вводить", "/ˌɪntrəˈduːs/", "A2", "Let me introduce our new developer."),
      w("marry", "жениться, выходить замуж", "/ˈmæri/", "A2", "They married last year."),
      w("prepare", "готовить(ся)", "/prɪˈpɛr/", "A2", "I need to prepare for the demo."),
      w("sail", "плыть (под парусом)", "/seɪl/", "B1", "They sailed across the lake."),
      w("serious", "серьёзный", "/ˈsɪriəs/", "A2", "This is a serious security problem."),
      w("spend", "тратить; проводить (время)", "/spɛnd/", "A2", "I spent two hours on this bug."),
      w("strange", "странный", "/streɪndʒ/", "A2", "I get a strange error."),
      w("truth", "правда", "/truːθ/", "B1", "Tell me the truth."),
      w("wake", "просыпаться; будить", "/weɪk/", "A2", "I wake up at seven."),
    ],
    it: [
      w("log", "лог, журнал; записывать в лог", "/lɔːɡ/", "B2", "Check the logs for errors."),
      w("monitor", "монитор; отслеживать", "/ˈmɑːnɪtər/", "B1", "We monitor the servers all the time."),
      w("alert", "оповещение; предупреждать", "/əˈlɜːrt/", "B2", "I got an alert at 3 a.m."),
      w("metric", "метрика, показатель", "/ˈmɛtrɪk/", "C1", "Response time is our key metric."),
      w("dashboard", "дашборд, панель мониторинга", "/ˈdæʃbɔːrd/", "B2", "All the metrics are on the dashboard."),
    ],
  },
  {
    book: [
      w("alone", "один, в одиночестве", "/əˈloʊn/", "A2", "I prefer to work alone."),
      w("apartment", "квартира", "/əˈpɑːrtmənt/", "A1", "I rent a small apartment."),
      w("article", "статья", "/ˈɑːrtɪkəl/", "A2", "I read an interesting article about Rust."),
      w("artist", "художник, артист", "/ˈɑːrtɪst/", "A2", "She is an artist and a designer."),
      w("attitude", "отношение", "/ˈætɪtuːd/", "B1", "He has a positive attitude."),
      w("compare", "сравнивать", "/kəmˈpɛr/", "A2", "Compare the two files."),
      w("judge", "судить, оценивать; судья", "/dʒʌdʒ/", "B1", "Don't judge people by their code."),
      w("magazine", "журнал", "/ˈmæɡəziːn/", "A1", "I read a tech magazine."),
      w("material", "материал", "/məˈtɪriəl/", "B1", "Here are the materials for the course."),
      w("meal", "еда, приём пищи", "/miːl/", "A2", "Let's have a meal after work."),
      w("method", "метод, способ", "/ˈmɛθəd/", "B1", "This method returns the user's name."),
      w("neighbor", "сосед", "/ˈneɪbər/", "A2", "My neighbor is a developer too."),
      w("professional", "профессиональный; профессионал", "/prəˈfɛʃənəl/", "B1", "She is a real professional."),
      w("profit", "прибыль", "/ˈprɑːfɪt/", "B1", "The company made a profit this year."),
      w("quality", "качество", "/ˈkwɑːləti/", "B1", "Code quality is important."),
      w("shape", "форма, фигура", "/ʃeɪp/", "B1", "The button has a round shape."),
      w("space", "пространство, место; пробел", "/speɪs/", "A2", "There is no space left on the disk."),
      w("stair", "ступенька; (stairs) лестница", "/stɛr/", "A2", "Take the stairs, not the elevator."),
      w("symbol", "символ", "/ˈsɪmbəl/", "B1", "The @ symbol is used in emails."),
      w("thin", "тонкий, худой", "/θɪn/", "A2", "This laptop is very thin."),
    ],
    it: [
      w("backup", "резервная копия", "/ˈbækʌp/", "B1", "We make a backup every night."),
      w("restore", "восстанавливать", "/rɪˈstɔːr/", "B2", "Restore the database from the backup."),
      w("storage", "хранилище; хранение", "/ˈstɔːrɪdʒ/", "B1", "We need more storage."),
      w("disk", "диск", "/dɪsk/", "B1", "The disk is almost full."),
      w("upload", "загружать (на сервер)", "/ˈʌploʊd/", "B1", "Upload your photo here."),
    ],
  },
  {
    book: [
      w("blood", "кровь", "/blʌd/", "A2", "He cut his finger and saw blood."),
      w("burn", "гореть; жечь", "/bɜːrn/", "A2", "Don't burn yourself on the coffee."),
      w("cell", "клетка; камера; ячейка (таблицы)", "/sɛl/", "B1", "Type the number in this cell."),
      w("contain", "содержать", "/kənˈteɪn/", "B1", "The file contains user data."),
      w("correct", "правильный; исправлять", "/kəˈrɛkt/", "A2", "Is this answer correct?"),
      w("crop", "урожай; сельскохозяйственная культура", "/krɑːp/", "B2", "Rice is the main crop here."),
      w("demand", "требовать; спрос", "/dɪˈmænd/", "B1", "The client demands a fix today."),
      w("equal", "равный", "/ˈiːkwəl/", "B1", "These two values are equal."),
      w("feed", "кормить; лента (новостей)", "/fiːd/", "B1", "Did you feed the cat?"),
      w("hole", "дыра", "/hoʊl/", "A2", "There is a hole in our security."),
      w("increase", "увеличивать(ся)", "/ɪnˈkriːs/", "B1", "The number of users increased."),
      w("lord", "лорд, господин", "/lɔːrd/", "B2", "The lord lived in a castle."),
      w("owe", "быть должным", "/oʊ/", "B1", "I owe you a coffee."),
      w("position", "положение; должность", "/pəˈzɪʃən/", "B1", "Change the position of the button."),
      w("raise", "поднимать", "/reɪz/", "B1", "Raise your hand if you have a question."),
      w("responsible", "ответственный", "/rɪˈspɑːnsəbəl/", "B1", "Who is responsible for the release?"),
      w("sight", "вид, зрелище; зрение", "/saɪt/", "B1", "The city at night is a beautiful sight."),
      w("spot", "место; пятно", "/spɑːt/", "B1", "This is a nice spot for lunch."),
      w("structure", "структура; сооружение", "/ˈstrʌktʃər/", "B1", "The project has a clear structure."),
      w("whole", "весь, целый", "/hoʊl/", "A2", "I spent the whole day in meetings."),
    ],
    it: [
      w("security", "безопасность", "/sɪˈkjʊrəti/", "B1", "Security is everyone's job."),
      w("vulnerability", "уязвимость", "/ˌvʌlnərəˈbɪləti/", "C1", "They found a vulnerability in the login form."),
      w("encryption", "шифрование", "/ɪnˈkrɪpʃən/", "C1", "All the data is protected by encryption."),
      w("permission", "разрешение; права доступа", "/pərˈmɪʃən/", "B1", "You don't have permission to edit this file."),
      w("access", "доступ; получать доступ", "/ˈæksɛs/", "B1", "I need access to the server."),
    ],
  },
  {
    book: [
      w("coach", "тренер", "/koʊtʃ/", "B1", "Our coach helps us grow."),
      w("control", "контролировать; управление", "/kənˈtroʊl/", "B1", "Version control saves a lot of time."),
      w("description", "описание", "/dɪˈskrɪpʃən/", "A2", "Add a short description to your pull request."),
      w("direct", "прямой", "/dəˈrɛkt/", "B1", "Is there a direct flight?"),
      w("exam", "экзамен", "/ɪɡˈzæm/", "A2", "I passed my English exam."),
      w("example", "пример", "/ɪɡˈzæmpəl/", "A1", "Can you give me an example?"),
      w("limit", "предел, лимит; ограничивать", "/ˈlɪmɪt/", "B1", "The API has a limit of 100 requests per minute."),
      w("local", "местный; локальный", "/ˈloʊkəl/", "A2", "It works on my local machine."),
      w("magical", "волшебный", "/ˈmædʒɪkəl/", "B1", "There is nothing magical about good code."),
      w("mail", "почта", "/meɪl/", "A2", "Did you check the mail?"),
      w("novel", "роман", "/ˈnɑːvəl/", "B1", "I am reading a novel in English."),
      w("outline", "план, набросок", "/ˈaʊtlaɪn/", "B2", "Write an outline of your talk first."),
      w("poet", "поэт", "/ˈpoʊət/", "B1", "Pushkin was a great poet."),
      w("print", "печатать; выводить", "/prɪnt/", "A2", "Print the value to the console."),
      w("scene", "сцена", "/siːn/", "B1", "The last scene of the film was sad."),
      w("sheet", "лист", "/ʃiːt/", "B1", "Give me a sheet of paper."),
      w("silly", "глупый", "/ˈsɪli/", "A2", "Sorry, it was a silly mistake."),
      w("store", "магазин; хранить", "/stɔːr/", "A2", "We store images in the cloud."),
      w("suffer", "страдать", "/ˈsʌfər/", "B1", "Users suffer when the app is slow."),
      w("technology", "технология", "/tɛkˈnɑːlədʒi/", "A2", "Technology changes fast."),
    ],
    it: [
      w("credentials", "учётные данные (логин и пароль)", "/krəˈdɛnʃəlz/", "C1", "Never share your credentials."),
      w("authorization", "авторизация", "/ˌɔːθərəˈzeɪʃən/", "C1", "Authorization decides what a user can do."),
      w("session", "сессия, сеанс", "/ˈsɛʃən/", "B1", "Your session has expired."),
      w("cookie", "cookie (файл куки); печенье", "/ˈkʊki/", "A2", "The site saves a cookie in your browser."),
      w("header", "заголовок", "/ˈhɛdər/", "B2", "Send the token in the header."),
    ],
  },
  {
    book: [
      w("across", "через, поперёк", "/əˈkrɔːs/", "A2", "The bank is across the street."),
      w("breathe", "дышать", "/briːð/", "B1", "Breathe — it's only a demo."),
      w("characteristic", "характерный; характеристика", "/ˌkærəktəˈrɪstɪk/", "B2", "Speed is a key characteristic of this tool."),
      w("consume", "потреблять", "/kənˈsuːm/", "B2", "This process consumes a lot of memory."),
      w("excite", "волновать, вызывать интерес", "/ɪkˈsaɪt/", "B2", "New projects excite me."),
      w("extreme", "крайний, чрезвычайный", "/ɪkˈstriːm/", "B1", "This is an extreme case."),
      w("fear", "страх; бояться", "/fɪr/", "B1", "Don't let fear stop you from speaking."),
      w("fortunate", "удачливый, счастливый", "/ˈfɔːrtʃənət/", "B2", "We were fortunate to have a backup."),
      w("happen", "происходить", "/ˈhæpən/", "A2", "What happened to the server?"),
      w("length", "длина", "/lɛŋθ/", "B1", "Check the length of the password."),
      w("mistake", "ошибка", "/mɪˈsteɪk/", "A2", "Everybody makes mistakes."),
      w("observe", "наблюдать", "/əbˈzɜːrv/", "B1", "Observe how users click the buttons."),
      w("opportunity", "возможность", "/ˌɑːpərˈtuːnəti/", "B1", "This job is a great opportunity."),
      w("prize", "приз", "/praɪz/", "A2", "Our team won first prize at the hackathon."),
      w("race", "гонка", "/reɪs/", "A2", "Who won the race?"),
      w("realize", "осознавать", "/ˈriːəlaɪz/", "B1", "I realized my mistake too late."),
      w("respond", "отвечать, реагировать", "/rɪˈspɑːnd/", "B1", "The server doesn't respond."),
      w("risk", "риск", "/rɪsk/", "B1", "Deploying on Friday is a risk."),
      w("wonder", "интересоваться, задаваться вопросом", "/ˈwʌndər/", "B1", "I wonder why the test fails."),
      w("yet", "ещё (в отрицании); уже (в вопросе)", "/jɛt/", "A2", "I haven't finished yet."),
    ],
    it: [
      w("query", "запрос", "/ˈkwɪri/", "B2", "This query is too slow."),
      w("table", "таблица; стол", "/ˈteɪbəl/", "A1", "Add a new table to the database."),
      w("row", "строка (таблицы); ряд", "/roʊ/", "A2", "The table has a thousand rows."),
      w("column", "столбец, колонка", "/ˈkɑːləm/", "B1", "Add a column for the email."),
      w("index", "индекс", "/ˈɪndɛks/", "B2", "An index makes the query faster."),
    ],
  },
  {
    book: [
      w("academy", "академия", "/əˈkædəmi/", "B2", "He studied at a music academy."),
      w("ancient", "древний", "/ˈeɪnʃənt/", "B1", "This server runs an ancient version of PHP."),
      w("board", "доска; совет (директоров)", "/bɔːrd/", "A2", "Write it on the board."),
      w("century", "век, столетие", "/ˈsɛntʃəri/", "A2", "The building is two centuries old."),
      w("clue", "подсказка, ключ (к разгадке)", "/kluː/", "B1", "The logs gave us a clue."),
      w("concert", "концерт", "/ˈkɑːnsərt/", "A2", "We went to a concert on Friday."),
      w("county", "округ, графство", "/ˈkaʊnti/", "B2", "He lives in a small county in Texas."),
      w("dictionary", "словарь", "/ˈdɪkʃənɛri/", "A1", "Use a dictionary only when you need it."),
      w("exist", "существовать", "/ɪɡˈzɪst/", "B1", "This file doesn't exist."),
      w("flat", "плоский; квартира (брит.)", "/flæt/", "B1", "Modern design is flat and simple."),
      w("gentleman", "джентльмен", "/ˈdʒɛntəlmən/", "B1", "He is a real gentleman."),
      w("hidden", "скрытый", "/ˈhɪdən/", "B1", "The setting is hidden in the menu."),
      w("maybe", "может быть", "/ˈmeɪbi/", "A1", "Maybe we can talk tomorrow."),
      w("officer", "офицер; должностное лицо", "/ˈɔːfɪsər/", "A2", "A police officer helped us."),
      w("original", "оригинальный, исходный", "/əˈrɪdʒənəl/", "B1", "Keep the original file."),
      w("pound", "колотить, стучать; фунт", "/paʊnd/", "B2", "He pounded on the door."),
      w("process", "процесс", "/ˈprɑːsɛs/", "B1", "The hiring process takes a month."),
      w("publish", "публиковать", "/ˈpʌblɪʃ/", "B1", "We published the package on npm."),
      w("theater", "театр", "/ˈθiːətər/", "A1", "We went to the theater last night."),
      w("wealth", "богатство", "/wɛlθ/", "B2", "Knowledge is real wealth."),
    ],
    it: [
      w("schema", "схема (базы данных)", "/ˈskiːmə/", "C1", "Update the database schema."),
      w("migration", "миграция", "/maɪˈɡreɪʃən/", "B2", "Run the migration before you deploy."),
      w("transaction", "транзакция", "/trænˈzækʃən/", "B2", "The payment runs in one transaction."),
      w("join", "присоединяться; объединять (таблицы)", "/dʒɔɪn/", "A2", "Join the two tables by user ID."),
      w("constraint", "ограничение", "/kənˈstreɪnt/", "C1", "A unique constraint stops duplicates."),
    ],
  },
  {
    book: [
      w("appreciate", "ценить, быть благодарным", "/əˈpriːʃieɪt/", "B1", "I appreciate your help."),
      w("available", "доступный, свободный", "/əˈveɪləbəl/", "A2", "Are you available for a call?"),
      w("beat", "побеждать, обыгрывать; бить", "/biːt/", "B1", "Our app beats the competitors on speed."),
      w("bright", "яркий", "/braɪt/", "A2", "The screen is too bright."),
      w("celebrate", "праздновать", "/ˈsɛləbreɪt/", "A2", "We celebrated the release with pizza."),
      w("determine", "определять", "/dɪˈtɜːrmɪn/", "B2", "We need to determine the cause."),
      w("disappear", "исчезать", "/ˌdɪsəˈpɪr/", "A2", "My changes disappeared after the merge."),
      w("else", "ещё; другой", "/ɛls/", "A2", "Anything else?"),
      w("fair", "справедливый", "/fɛr/", "B1", "That's a fair point."),
      w("flow", "течь; поток", "/floʊ/", "B1", "The data flows from the API to the UI."),
      w("forward", "вперёд; пересылать", "/ˈfɔːrwərd/", "A2", "I'll forward you the email."),
      w("hill", "холм", "/hɪl/", "A2", "Our office is on a hill."),
      w("lone", "одинокий, единственный", "/loʊn/", "B2", "A lone developer built the whole app."),
      w("puddle", "лужа", "/ˈpʌdəl/", "B2", "He stepped into a puddle."),
      w("season", "время года; сезон", "/ˈsiːzən/", "A2", "Summer is my favorite season."),
      w("solution", "решение", "/səˈluːʃən/", "A2", "We need a quick solution."),
      w("waste", "тратить впустую; отходы", "/weɪst/", "B1", "Don't waste time on long meetings."),
      w("whether", "ли (при выборе между вариантами)", "/ˈwɛðər/", "B1", "I don't know whether it works."),
    ],
    it: [
      w("clone", "клонировать", "/kloʊn/", "B2", "Clone the repository to your laptop."),
      w("fork", "форк; делать форк", "/fɔːrk/", "B2", "Fork the project on GitHub."),
      w("push", "отправлять (git push); толкать", "/pʊʃ/", "A2", "Push your changes to the branch."),
      w("pull", "подтягивать изменения (git pull); тянуть", "/pʊl/", "A2", "Pull the latest changes first."),
      w("conflict", "конфликт", "/ˈkɑːnflɪkt/", "B1", "There is a merge conflict in this file."),
    ],
  },
  {
    book: [
      w("argue", "спорить", "/ˈɑːrɡjuː/", "B1", "We argued about tabs and spaces."),
      w("communicate", "общаться", "/kəˈmjuːnɪkeɪt/", "B1", "Good teams communicate a lot."),
      w("crowd", "толпа", "/kraʊd/", "B1", "There was a big crowd at the conference."),
      w("depend", "зависеть", "/dɪˈpɛnd/", "A2", "It depends on the browser."),
      w("dish", "блюдо; тарелка", "/dɪʃ/", "A2", "This is my favorite dish."),
      w("empty", "пустой", "/ˈɛmpti/", "A2", "The list is empty."),
      w("exact", "точный", "/ɪɡˈzækt/", "B1", "What is the exact error message?"),
      w("fresh", "свежий", "/frɛʃ/", "A2", "Start with a fresh install."),
      w("gather", "собирать(ся)", "/ˈɡæðər/", "B1", "We gathered feedback from users."),
      w("indicate", "указывать, означать", "/ˈɪndɪkeɪt/", "B2", "A red icon indicates an error."),
      w("item", "пункт, элемент, предмет", "/ˈaɪtəm/", "A2", "Add the item to the cart."),
      w("offer", "предлагать; предложение", "/ˈɔːfər/", "A2", "They offered me a job."),
      w("price", "цена", "/praɪs/", "A1", "The price of the plan went up."),
      w("product", "продукт", "/ˈprɑːdʌkt/", "A2", "Our product helps small shops."),
      w("property", "собственность; свойство", "/ˈprɑːpərti/", "B1", "Every object has properties."),
      w("purchase", "покупать; покупка", "/ˈpɜːrtʃəs/", "B1", "You can purchase a license online."),
      w("recommend", "рекомендовать", "/ˌrɛkəˈmɛnd/", "B1", "Can you recommend a good book?"),
      w("select", "выбирать", "/sɪˈlɛkt/", "B1", "Select a file from the list."),
      w("tool", "инструмент", "/tuːl/", "A2", "Git is a very useful tool."),
      w("treat", "обращаться (с кем-то); угощать", "/triːt/", "B1", "Treat your colleagues with respect."),
    ],
    it: [
      w("tag", "тег, метка", "/tæɡ/", "B1", "Add a tag for each release."),
      w("changelog", "журнал изменений", "/ˈtʃeɪndʒlɔːɡ/", "C1", "Update the changelog before the release."),
      w("hotfix", "срочное исправление", "/ˈhɑːtfɪks/", "C1", "We shipped a hotfix in an hour."),
      w("rollback", "откат", "/ˈroʊlbæk/", "C1", "After the failed deploy we did a rollback."),
      w("patch", "патч, заплатка", "/pætʃ/", "B2", "Install the security patch today."),
    ],
  },
  {
    book: [
      w("alive", "живой", "/əˈlaɪv/", "A2", "Is the server still alive?"),
      w("bone", "кость", "/boʊn/", "A2", "He broke a bone in his arm."),
      w("bother", "беспокоить; утруждать себя", "/ˈbɑːðər/", "B1", "Sorry to bother you, but the build is red."),
      w("captain", "капитан", "/ˈkæptɪn/", "A2", "The captain spoke to the passengers."),
      w("conclusion", "вывод, заключение", "/kənˈkluːʒən/", "B1", "What is your conclusion?"),
      w("doubt", "сомнение; сомневаться", "/daʊt/", "B1", "I have no doubt it will work."),
      w("explore", "исследовать", "/ɪkˈsplɔːr/", "B1", "Explore the code before you change it."),
      w("foreign", "иностранный", "/ˈfɔːrən/", "A2", "English is a foreign language for me."),
      w("glad", "довольный, рад", "/ɡlæd/", "A2", "I'm glad you like it."),
      w("however", "однако", "/haʊˈɛvər/", "A2", "The idea is good; however, it is too expensive."),
      w("injustice", "несправедливость", "/ɪnˈdʒʌstɪs/", "C1", "He spoke about injustice in the world."),
      w("international", "международный", "/ˌɪntərˈnæʃənəl/", "A2", "We work in an international team."),
      w("lawyer", "юрист, адвокат", "/ˈlɔːjər/", "A2", "Ask a lawyer about the license."),
      w("mention", "упоминать", "/ˈmɛnʃən/", "B1", "You didn't mention the deadline."),
      w("policy", "политика, правила", "/ˈpɑːləsi/", "B1", "Read the privacy policy."),
      w("social", "социальный, общественный", "/ˈsoʊʃəl/", "A2", "I don't use social networks much."),
      w("speech", "речь", "/spiːtʃ/", "B1", "He gave a short speech at the party."),
      w("staff", "персонал, сотрудники", "/stæf/", "B1", "All staff must use strong passwords."),
      w("toward", "к, по направлению к", "/tɔːrd/", "B1", "We are moving toward our goal."),
      w("wood", "дерево (материал), древесина", "/wʊd/", "A2", "The table is made of wood."),
    ],
    it: [
      w("staging", "тестовая среда (staging)", "/ˈsteɪdʒɪŋ/", "C1", "Test it on staging first."),
      w("production", "продакшн, рабочая среда; производство", "/prəˈdʌkʃən/", "B1", "Never test in production."),
      w("configuration", "конфигурация, настройки", "/kənˌfɪɡjəˈreɪʃən/", "C1", "Check the configuration file."),
      w("container", "контейнер", "/kənˈteɪnər/", "B1", "The app runs in a Docker container."),
      w("cluster", "кластер", "/ˈklʌstər/", "C1", "Our cluster has ten servers."),
    ],
  },
  {
    book: [
      w("achieve", "достигать", "/əˈtʃiːv/", "B1", "We achieved our goal this sprint."),
      w("advise", "советовать", "/ədˈvaɪz/", "B1", "I advise you to update the library."),
      w("already", "уже", "/ɔːlˈrɛdi/", "A2", "I have already fixed it."),
      w("basic", "базовый, основной", "/ˈbeɪsɪk/", "A2", "This course covers the basic ideas."),
      w("bit", "кусочек, немного; бит", "/bɪt/", "A2", "Wait a bit, please."),
      w("consider", "рассматривать, обдумывать", "/kənˈsɪdər/", "B1", "Consider all the options."),
      w("destroy", "уничтожать", "/dɪˈstrɔɪ/", "B1", "One command can destroy the database."),
      w("entertain", "развлекать", "/ˌɛntərˈteɪn/", "B1", "The game entertains millions of people."),
      w("extra", "дополнительный", "/ˈɛkstrə/", "A2", "This feature needs extra work."),
      w("goal", "цель", "/ɡoʊl/", "A2", "What is the goal of this sprint?"),
      w("lie", "лгать; ложь", "/laɪ/", "B1", "Don't lie about your progress."),
      w("meat", "мясо", "/miːt/", "A1", "I don't eat meat."),
      w("opinion", "мнение", "/əˈpɪnjən/", "A2", "In my opinion, the design is great."),
      w("real", "настоящий, реальный", "/ˈriːəl/", "A2", "Test it with real users."),
      w("reflect", "отражать", "/rɪˈflɛkt/", "B2", "The screen reflects the light."),
      w("regard", "считать, рассматривать (как)", "/rɪˈɡɑːrd/", "B2", "She is regarded as the best tester."),
      w("serve", "обслуживать; подавать", "/sɜːrv/", "A2", "This server serves static files."),
      w("vegetable", "овощ", "/ˈvɛdʒtəbəl/", "A1", "Eat more vegetables."),
      w("war", "война", "/wɔːr/", "A2", "They never talk about the war."),
      w("worth", "стоящий; стоимостью", "/wɜːrθ/", "B1", "The course is worth the money."),
    ],
    it: [
      w("pipeline", "пайплайн, конвейер", "/ˈpaɪplaɪn/", "C1", "The pipeline runs all the tests."),
      w("continuous integration", "непрерывная интеграция (CI)", "/kənˈtɪnjuəs ˌɪntɪˈɡreɪʃən/", "C1", "Continuous integration checks every commit."),
      w("automate", "автоматизировать", "/ˈɔːtəmeɪt/", "B2", "Automate boring tasks."),
      w("workflow", "рабочий процесс", "/ˈwɜːrkfloʊ/", "C1", "This workflow deploys the app."),
      w("trigger", "запускать, вызывать; триггер", "/ˈtrɪɡər/", "B2", "Each push triggers a build."),
    ],
  },
  {
    book: [
      w("appear", "появляться; казаться", "/əˈpɪr/", "A2", "An error appears on the screen."),
      w("base", "основа, база", "/beɪs/", "B1", "This code is the base for the new app."),
      w("brain", "мозг", "/breɪn/", "A2", "My brain is tired after this meeting."),
      w("career", "карьера", "/kəˈrɪr/", "A2", "She started her career as a tester."),
      w("clerk", "клерк, служащий", "/klɜːrk/", "B1", "The bank clerk helped me."),
      w("effort", "усилие", "/ˈɛfərt/", "B1", "This task needs a lot of effort."),
      w("enter", "входить; вводить", "/ˈɛntər/", "A2", "Enter your password."),
      w("excellent", "отличный", "/ˈɛksələnt/", "A1", "Excellent work!"),
      w("hero", "герой", "/ˈhɪroʊ/", "A2", "You are my hero — you fixed it!"),
      w("hurry", "спешить", "/ˈhɜːri/", "A2", "Don't hurry — check everything."),
      w("inform", "сообщать, информировать", "/ɪnˈfɔːrm/", "B1", "Please inform the team about the change."),
      w("later", "позже", "/ˈleɪtər/", "A1", "Let's talk later."),
      w("leave", "уходить, покидать; оставлять", "/liːv/", "A1", "I leave the office at six."),
      w("locate", "находить; располагать", "/ˈloʊkeɪt/", "B2", "We located the bug in the payment code."),
      w("nurse", "медсестра, медбрат", "/nɜːrs/", "A1", "My sister is a nurse."),
      w("operation", "операция", "/ˌɑːpəˈreɪʃən/", "B1", "This operation takes a few seconds."),
      w("pain", "боль", "/peɪn/", "A2", "Merge conflicts are a pain."),
      w("refuse", "отказываться", "/rɪˈfjuːz/", "B1", "The server refused the connection."),
      w("though", "хотя", "/ðoʊ/", "B1", "It works, though it is slow."),
      w("various", "различный, разнообразный", "/ˈvɛriəs/", "B1", "We tested it on various devices."),
    ],
    it: [
      w("requirement", "требование", "/rɪˈkwaɪərmənt/", "B2", "Read the requirements before you start."),
      w("specification", "спецификация", "/ˌspɛsɪfɪˈkeɪʃən/", "C1", "The specification describes every screen."),
      w("estimate", "оценка; оценивать", "/ˈɛstɪmeɪt/", "B1", "Can you estimate this task?"),
      w("priority", "приоритет", "/praɪˈɔːrəti/", "B1", "Security is our top priority."),
      w("backlog", "бэклог, список задач", "/ˈbæklɔːɡ/", "C1", "Add this idea to the backlog."),
    ],
  },
  {
    book: [
      w("actual", "фактический, настоящий", "/ˈæktʃuəl/", "B1", "The actual result is different from the expected one."),
      w("amaze", "изумлять", "/əˈmeɪz/", "B1", "The speed of the new version amazed us."),
      w("charge", "плата; заряжать", "/tʃɑːrdʒ/", "B1", "There is no charge for this service."),
      w("comfort", "утешать; комфорт", "/ˈkʌmfərt/", "B1", "She comforted her friend."),
      w("contact", "связываться; контакт", "/ˈkɑːntækt/", "A2", "Contact support if you have problems."),
      w("customer", "клиент, покупатель", "/ˈkʌstəmər/", "A2", "The customer is always right."),
      w("deliver", "доставлять; выпускать (фичи)", "/dɪˈlɪvər/", "B1", "We deliver new features every two weeks."),
      w("earn", "зарабатывать", "/ɜːrn/", "A2", "Developers earn good money."),
      w("gate", "ворота, калитка; выход (в аэропорту)", "/ɡeɪt/", "A2", "Our flight leaves from gate 12."),
      w("include", "включать", "/ɪnˈkluːd/", "A2", "The price includes support."),
      w("manage", "управлять; справляться", "/ˈmænɪdʒ/", "B1", "She manages a team of ten."),
      w("mystery", "загадка, тайна", "/ˈmɪstəri/", "B1", "Why it works is a mystery."),
      w("occur", "происходить", "/əˈkɜːr/", "B1", "The error occurs only on Mondays."),
      w("opposite", "противоположность; противоположный", "/ˈɑːpəzɪt/", "A2", "Fast is the opposite of slow."),
      w("plate", "тарелка", "/pleɪt/", "A2", "Put the plate on the table."),
      w("receive", "получать", "/rɪˈsiːv/", "A2", "Did you receive my message?"),
      w("reward", "награда", "/rɪˈwɔːrd/", "B1", "The reward for finding a bug is $500."),
      w("set", "устанавливать, ставить; набор", "/sɛt/", "A2", "Set the value to zero."),
      w("steal", "красть", "/stiːl/", "B1", "Hackers stole user passwords."),
      w("thief", "вор", "/θiːf/", "B1", "The thief took my laptop."),
    ],
    it: [
      w("ticket", "тикет, заявка; билет", "/ˈtɪkɪt/", "A2", "Create a ticket for this bug."),
      w("milestone", "этап, веха", "/ˈmaɪlstoʊn/", "C1", "The first milestone is in March."),
      w("roadmap", "дорожная карта, план развития", "/ˈroʊdmæp/", "C1", "This feature is on our roadmap."),
      w("stakeholder", "заинтересованная сторона", "/ˈsteɪkhoʊldər/", "C1", "Show the demo to all the stakeholders."),
      w("kickoff", "старт проекта, стартовая встреча", "/ˈkɪkɔːf/", "C1", "The project kickoff is on Monday."),
    ],
  },
  {
    book: [
      w("advance", "продвигаться; прогресс", "/ədˈvæns/", "B2", "Technology advances very fast."),
      w("athlete", "спортсмен", "/ˈæθliːt/", "B1", "She is a professional athlete."),
      w("average", "средний", "/ˈævərɪdʒ/", "B1", "The average response time is 200 ms."),
      w("behavior", "поведение", "/bɪˈheɪvjər/", "B1", "This is expected behavior."),
      w("behind", "позади, за", "/bɪˈhaɪnd/", "A1", "We are behind schedule."),
      w("course", "курс", "/kɔːrs/", "A2", "I took an online course in SQL."),
      w("lower", "опускать, понижать", "/ˈloʊər/", "B1", "We lowered the price."),
      w("match", "совпадать; матч", "/mætʃ/", "A2", "The passwords don't match."),
      w("member", "член, участник", "/ˈmɛmbər/", "A2", "She is a new member of our team."),
      w("mental", "психический, умственный", "/ˈmɛntəl/", "B2", "Mental health is important."),
      w("passenger", "пассажир", "/ˈpæsɪndʒər/", "A2", "The passengers waited for the train."),
      w("personality", "личность, характер", "/ˌpɜːrsəˈnæləti/", "B1", "He has a great personality."),
      w("poem", "стихотворение", "/ˈpoʊəm/", "A2", "She wrote a poem in English."),
      w("pole", "столб, шест; полюс", "/poʊl/", "B1", "The camera is on a tall pole."),
      w("remove", "удалять", "/rɪˈmuːv/", "B1", "Remove the old code."),
      w("safety", "безопасность", "/ˈseɪfti/", "B1", "Safety comes first."),
      w("shoot", "стрелять; снимать (видео)", "/ʃuːt/", "B1", "We shot a short video for the demo."),
      w("sound", "звук; звучать", "/saʊnd/", "A2", "That sounds like a good plan."),
      w("swim", "плавать", "/swɪm/", "A1", "I swim every morning."),
      w("web", "веб, интернет; паутина", "/wɛb/", "A2", "We build apps for the web."),
    ],
    it: [
      w("retrospective", "ретроспектива", "/ˌrɛtrəˈspɛktɪv/", "C1", "At the retrospective we talk about the sprint."),
      w("demo", "демо, демонстрация", "/ˈdɛmoʊ/", "B1", "The demo is at three o'clock."),
      w("feedback", "обратная связь", "/ˈfiːdbæk/", "B1", "Thanks for the feedback!"),
      w("blocker", "блокер, блокирующая проблема", "/ˈblɑːkər/", "C1", "Do you have any blockers today?"),
      w("scope", "объём работ, рамки", "/skoʊp/", "C1", "This is out of scope for this sprint."),
    ],
  },
  {
    book: [
      w("block", "квартал; блок; блокировать", "/blɑːk/", "A2", "The office is two blocks from here."),
      w("cheer", "подбадривать, приветствовать криками", "/tʃɪr/", "B1", "Everybody cheered when the tests passed."),
      w("complex", "сложный", "/ˈkɑːmplɛks/", "B1", "This code is too complex."),
      w("critic", "критик", "/ˈkrɪtɪk/", "B1", "The critic liked the film."),
      w("event", "событие", "/ɪˈvɛnt/", "A2", "The button fires a click event."),
      w("exercise", "упражнение; тренироваться", "/ˈɛksərsaɪz/", "A2", "Do this exercise every day."),
      w("fit", "подходить (по размеру), помещаться", "/fɪt/", "A2", "The text doesn't fit on the screen."),
      w("friendship", "дружба", "/ˈfrɛndʃɪp/", "B1", "Their friendship started at work."),
      w("guide", "гид; руководство", "/ɡaɪd/", "A2", "Read the setup guide."),
      w("lack", "нехватка; не хватать", "/læk/", "B1", "The project lacks documentation."),
      w("passage", "проход, коридор; отрывок (текста)", "/ˈpæsɪdʒ/", "B1", "Read the passage and answer the questions."),
      w("perform", "выполнять; выступать", "/pərˈfɔːrm/", "B1", "The app performs well under load."),
      w("pressure", "давление", "/ˈprɛʃər/", "B1", "We work under a lot of pressure."),
      w("probable", "вероятный", "/ˈprɑːbəbəl/", "B2", "A network error is the probable cause."),
      w("public", "общественный, публичный", "/ˈpʌblɪk/", "A2", "This repository is public."),
      w("strike", "ударять; забастовка", "/straɪk/", "B1", "Lightning struck the tree."),
      w("support", "поддерживать; поддержка", "/səˈpɔːrt/", "A2", "Does the app support dark mode?"),
      w("term", "термин; срок", "/tɜːrm/", "B1", "\"Deploy\" is a common IT term."),
      w("unite", "объединять(ся)", "/juˈnaɪt/", "B2", "The project united people from ten countries."),
    ],
    it: [
      w("refactor", "рефакторить", "/riːˈfæktər/", "C1", "Let's refactor this function."),
      w("legacy", "устаревший (о коде); наследие", "/ˈlɛɡəsi/", "C1", "We still support legacy code."),
      w("technical debt", "технический долг", "/ˈtɛknɪkəl dɛt/", "C1", "Technical debt slows us down."),
      w("readable", "читаемый", "/ˈriːdəbəl/", "B2", "Write readable code."),
      w("maintainable", "поддерживаемый (о коде)", "/meɪnˈteɪnəbəl/", "C1", "Small functions are more maintainable."),
    ],
  },
  {
    book: [
      w("associate", "ассоциировать, связывать", "/əˈsoʊʃieɪt/", "B2", "I associate this song with summer."),
      w("environment", "окружение, среда", "/ɪnˈvaɪrənmənt/", "B1", "The test environment is ready."),
      w("factory", "фабрика, завод", "/ˈfæktəri/", "A2", "He works in a car factory."),
      w("instance", "пример; экземпляр", "/ˈɪnstəns/", "B1", "Start a new instance of the server."),
      w("involve", "вовлекать; включать в себя", "/ɪnˈvɑːlv/", "B1", "The task involves a lot of testing."),
      w("medicine", "лекарство; медицина", "/ˈmɛdɪsən/", "A2", "Take this medicine twice a day."),
      w("mix", "смешивать", "/mɪks/", "A2", "Don't mix tabs and spaces."),
      w("organize", "организовывать", "/ˈɔːrɡənaɪz/", "A2", "Organize your files in folders."),
      w("period", "период", "/ˈpɪriəd/", "B1", "The trial period is 14 days."),
      w("populate", "населять; заполнять (данными)", "/ˈpɑːpjəleɪt/", "C1", "Populate the table with test data."),
      w("produce", "производить", "/prəˈduːs/", "B1", "The script produces a report."),
      w("range", "диапазон", "/reɪndʒ/", "B1", "The value must be in the range from 1 to 10."),
      w("recognize", "узнавать, распознавать", "/ˈrɛkəɡnaɪz/", "B1", "The app recognizes your voice."),
      w("regular", "регулярный, обычный", "/ˈrɛɡjələr/", "A2", "We have regular meetings."),
      w("sign", "знак, табличка; подписывать", "/saɪn/", "A2", "Sign the contract, please."),
      w("tip", "совет; кончик; чаевые", "/tɪp/", "B1", "Here is a tip: use keyboard shortcuts."),
      w("tradition", "традиция", "/trəˈdɪʃən/", "B1", "Pizza on Friday is our tradition."),
      w("trash", "мусор; корзина", "/træʃ/", "B1", "Move the file to the trash."),
      w("wide", "широкий", "/waɪd/", "A2", "The table is too wide for mobile."),
    ],
    it: [
      w("performance", "производительность", "/pərˈfɔːrməns/", "B1", "We improved the performance of the app."),
      w("latency", "задержка", "/ˈleɪtənsi/", "C1", "The latency is very low."),
      w("bandwidth", "пропускная способность канала", "/ˈbændwɪdθ/", "C1", "Video calls need a lot of bandwidth."),
      w("throughput", "пропускная способность (системы)", "/ˈθruːpʊt/", "C1", "The throughput is 1,000 requests per second."),
      w("bottleneck", "узкое место", "/ˈbɑːtəlnɛk/", "C1", "The database is our bottleneck."),
    ],
  },
  {
    book: [
      w("advice", "совет", "/ədˈvaɪs/", "A2", "Thanks for the advice."),
      w("along", "вдоль; с собой", "/əˈlɔːŋ/", "A2", "We walked along the river."),
      w("attention", "внимание", "/əˈtɛnʃən/", "A2", "Pay attention to the warnings."),
      w("attract", "привлекать", "/əˈtrækt/", "B1", "Good design attracts users."),
      w("climb", "взбираться", "/klaɪm/", "A2", "We climbed the mountain."),
      w("drop", "ронять; падать; снижение", "/drɑːp/", "A2", "I dropped my phone."),
      w("final", "последний, финальный", "/ˈfaɪnəl/", "A2", "This is the final version."),
      w("further", "дальше; дальнейший", "/ˈfɜːrðər/", "B1", "We need further tests."),
      w("imply", "подразумевать", "/ɪmˈplaɪ/", "B2", "What does this message imply?"),
      w("maintain", "поддерживать, обслуживать", "/meɪnˈteɪn/", "B1", "Two people maintain this library."),
      w("neither", "ни один (из двух)", "/ˈniːðər/", "B1", "Neither solution works."),
      w("otherwise", "иначе, в противном случае", "/ˈʌðərwaɪz/", "B1", "Save your work; otherwise, you will lose it."),
      w("physical", "физический", "/ˈfɪzɪkəl/", "B1", "We don't have physical servers anymore."),
      w("prove", "доказывать", "/pruːv/", "B1", "The tests prove that it works."),
      w("react", "реагировать", "/riˈækt/", "B1", "How did the client react?"),
      w("ride", "ездить (на велосипеде и т. п.)", "/raɪd/", "A2", "I ride my bike to work."),
      w("situated", "расположенный", "/ˈsɪtʃueɪtɪd/", "B2", "The office is situated near the station."),
      w("society", "общество", "/səˈsaɪəti/", "B1", "Technology changes society."),
      w("standard", "стандарт; стандартный", "/ˈstændərd/", "B1", "Follow the coding standard."),
      w("suggest", "предлагать, советовать", "/səɡˈdʒɛst/", "B1", "I suggest we take a break."),
    ],
    it: [
      w("scalability", "масштабируемость", "/ˌskeɪləˈbɪləti/", "C1", "Scalability is important for big apps."),
      w("load balancer", "балансировщик нагрузки", "/loʊd ˈbælənsər/", "C1", "The load balancer sends traffic to three servers."),
      w("traffic", "трафик; дорожное движение", "/ˈtræfɪk/", "A2", "Our traffic grows every month."),
      w("downtime", "время простоя", "/ˈdaʊntaɪm/", "C1", "We had ten minutes of downtime."),
      w("uptime", "время бесперебойной работы", "/ˈʌptaɪm/", "C1", "Our uptime is 99.9%."),
    ],
  },
  {
    book: [
      w("actually", "на самом деле", "/ˈæktʃuəli/", "A2", "Actually, the bug is in the backend."),
      w("bite", "кусать; укус", "/baɪt/", "A2", "The dog bit my hand."),
      w("coast", "побережье", "/koʊst/", "B1", "We live on the coast."),
      w("deal", "сделка, договорённость", "/diːl/", "B1", "OK, it's a deal."),
      w("desert", "пустыня", "/ˈdɛzərt/", "A2", "The desert is hot and dry."),
      w("earthquake", "землетрясение", "/ˈɜːrθkweɪk/", "B1", "The earthquake damaged many buildings."),
      w("effective", "эффективный", "/ɪˈfɛktɪv/", "B1", "Code review is an effective way to find bugs."),
      w("examine", "исследовать, изучать", "/ɪɡˈzæmɪn/", "B1", "Examine the logs carefully."),
      w("false", "ложный", "/fɔːls/", "A2", "The function returns false."),
      w("gift", "подарок", "/ɡɪft/", "A2", "Thank you for the gift!"),
      w("hunger", "голод", "/ˈhʌŋɡər/", "B2", "Hunger is a big problem in the world."),
      w("imagine", "представлять себе", "/ɪˈmædʒɪn/", "A2", "Imagine a world without the internet."),
      w("journey", "путешествие, поездка", "/ˈdʒɜːrni/", "A2", "Learning English is a long journey."),
      w("puzzle", "головоломка", "/ˈpʌzəl/", "B1", "This bug is a real puzzle."),
      w("quite", "довольно; вполне", "/kwaɪt/", "A2", "The task is quite easy."),
      w("rather", "скорее, предпочтительнее", "/ˈræðər/", "B1", "I'd rather work from home today."),
      w("specific", "конкретный, определённый", "/spəˈsɪfɪk/", "B1", "Can you be more specific?"),
      w("tour", "тур, экскурсия", "/tʊr/", "A2", "They gave us a tour of the office."),
      w("trip", "поездка", "/trɪp/", "A1", "I have a business trip next week."),
      w("value", "значение; ценность", "/ˈvæljuː/", "B1", "Set the value to true."),
    ],
    it: [
      w("component", "компонент", "/kəmˈpoʊnənt/", "B2", "Split the page into small components."),
      w("layout", "макет, расположение элементов", "/ˈleɪaʊt/", "B2", "The layout breaks on small screens."),
      w("responsive", "адаптивный (о дизайне)", "/rɪˈspɑːnsɪv/", "C1", "Our site is fully responsive."),
      w("accessibility", "доступность (для людей с ограничениями)", "/əkˌsɛsəˈbɪləti/", "C1", "Accessibility helps people with disabilities."),
      w("render", "отрисовывать, рендерить", "/ˈrɛndər/", "C1", "The page renders in 100 milliseconds."),
    ],
  },
  {
    book: [
      w("band", "музыкальная группа", "/bænd/", "A2", "My favorite band is playing tonight."),
      w("barely", "едва", "/ˈbɛrli/", "B2", "I could barely hear you on the call."),
      w("boring", "скучный", "/ˈbɔːrɪŋ/", "A1", "Writing documentation is boring, but important."),
      w("cancel", "отменять", "/ˈkænsəl/", "B1", "The meeting is canceled."),
      w("driveway", "подъездная дорожка", "/ˈdraɪvweɪ/", "C1", "His car is in the driveway."),
      w("garbage", "мусор", "/ˈɡɑːrbɪdʒ/", "B1", "Take out the garbage, please."),
      w("instrument", "инструмент (музыкальный, измерительный)", "/ˈɪnstrəmənt/", "A2", "Do you play an instrument?"),
      w("list", "список", "/lɪst/", "A1", "Make a list of tasks."),
      w("magic", "магия, волшебство", "/ˈmædʒɪk/", "B1", "It looks like magic, but it's just code."),
      w("message", "сообщение", "/ˈmɛsɪdʒ/", "A1", "Write a clear commit message."),
      w("notice", "замечать", "/ˈnoʊtɪs/", "B1", "Did you notice the error?"),
      w("own", "владеть; собственный", "/oʊn/", "A2", "Who owns this repository?"),
      w("predict", "предсказывать", "/prɪˈdɪkt/", "B1", "It is hard to predict how long it will take."),
      w("professor", "профессор", "/prəˈfɛsər/", "A2", "My professor taught me C."),
      w("rush", "спешить; спешка", "/rʌʃ/", "B1", "Don't rush the release."),
      w("share", "делиться; предоставлять доступ", "/ʃɛr/", "A2", "Share the link with the team."),
      w("stage", "сцена; этап", "/steɪdʒ/", "B1", "The project is at an early stage."),
      w("storm", "шторм, гроза", "/stɔːrm/", "A2", "A storm cut the power."),
      w("within", "в пределах, внутри", "/wɪˈðɪn/", "B1", "We will reply within 24 hours."),
    ],
    it: [
      w("protocol", "протокол", "/ˈproʊtəkɔːl/", "B2", "HTTP is a protocol."),
      w("status code", "код ответа (статус-код)", "/ˈsteɪtəs koʊd/", "C1", "The status code 404 means \"not found\"."),
      w("payload", "полезная нагрузка (данные запроса)", "/ˈpeɪloʊd/", "C1", "The payload is too big."),
      w("JSON", "JSON (формат данных)", "/ˈdʒeɪsən/", "C1", "The API returns JSON."),
      w("timeout", "тайм-аут", "/ˈtaɪmaʊt/", "C1", "The request failed with a timeout."),
    ],
  },
  {
    book: [
      w("advertise", "рекламировать", "/ˈædvərtaɪz/", "B1", "We advertise our app online."),
      w("assign", "назначать, поручать", "/əˈsaɪn/", "B2", "Assign the ticket to me."),
      w("audience", "аудитория", "/ˈɔːdiəns/", "B1", "Who is the audience for this app?"),
      w("breakfast", "завтрак", "/ˈbrɛkfəst/", "A1", "I have breakfast at eight."),
      w("competition", "конкуренция; соревнование", "/ˌkɑːmpəˈtɪʃən/", "B1", "There is a lot of competition in this market."),
      w("cool", "прохладный; классный", "/kuːl/", "A1", "That's a cool feature!"),
      w("gain", "получать, приобретать", "/ɡeɪn/", "B1", "You gain experience with every project."),
      w("importance", "важность", "/ɪmˈpɔːrtəns/", "B1", "Don't forget the importance of tests."),
      w("knowledge", "знание, знания", "/ˈnɑːlɪdʒ/", "B1", "Share your knowledge with the team."),
      w("major", "главный, крупный", "/ˈmeɪdʒər/", "B1", "This is a major update."),
      w("mean", "значить, иметь в виду; злой", "/miːn/", "A1", "What does this error mean?"),
      w("prefer", "предпочитать", "/prɪˈfɜːr/", "A2", "I prefer tabs."),
      w("president", "президент", "/ˈprɛzɪdənt/", "A2", "The president of the company visited us."),
      w("respect", "уважение; уважать", "/rɪˈspɛkt/", "B1", "Respect other people's time."),
      w("rich", "богатый", "/rɪtʃ/", "A2", "He became rich after the startup."),
      w("skill", "навык", "/skɪl/", "A2", "Communication is an important skill."),
      w("somehow", "как-то, каким-то образом", "/ˈsʌmhaʊ/", "B1", "Somehow, the test passes now."),
      w("strength", "сила; сильная сторона", "/strɛŋθ/", "B1", "What are your strengths?"),
      w("vote", "голосовать; голос", "/voʊt/", "B1", "Let's vote on the design."),
    ],
    it: [
      w("asynchronous", "асинхронный", "/eɪˈsɪŋkrənəs/", "C1", "This function is asynchronous."),
      w("callback", "колбэк, функция обратного вызова", "/ˈkɔːlbæk/", "C1", "Pass a callback to the function."),
      w("thread", "поток; ветка (обсуждения)", "/θrɛd/", "B2", "Answer in the thread, please."),
      w("concurrency", "параллелизм, конкурентность", "/kənˈkɜːrənsi/", "C1", "Concurrency bugs are hard to find."),
      w("race condition", "состояние гонки", "/reɪs kənˈdɪʃən/", "C1", "The crash was caused by a race condition."),
    ],
  },
  {
    book: [
      w("above", "над, выше", "/əˈbʌv/", "A1", "See the example above."),
      w("ahead", "впереди, вперёд", "/əˈhɛd/", "A2", "We are ahead of schedule."),
      w("amount", "количество", "/əˈmaʊnt/", "B1", "The amount of data grows every day."),
      w("belief", "убеждение, вера", "/bɪˈliːf/", "B1", "It is a common belief that tests are slow."),
      w("center", "центр", "/ˈsɛntər/", "A1", "Center the text on the page."),
      w("common", "общий; распространённый", "/ˈkɑːmən/", "A2", "This is a common mistake."),
      w("cost", "стоимость; стоить", "/kɔːst/", "A2", "How much does the server cost?"),
      w("demonstrate", "демонстрировать", "/ˈdɛmənstreɪt/", "B1", "Let me demonstrate the new feature."),
      w("evidence", "доказательство", "/ˈɛvɪdəns/", "B1", "Do you have any evidence of the bug?"),
      w("honesty", "честность", "/ˈɑːnəsti/", "B2", "Honesty is important in a team."),
      w("idiom", "идиома", "/ˈɪdiəm/", "B2", "\"Piece of cake\" is an idiom."),
      w("independent", "независимый", "/ˌɪndɪˈpɛndənt/", "B1", "Each test should be independent."),
      w("inside", "внутри", "/ɪnˈsaɪd/", "A1", "The config file is inside this folder."),
      w("master", "мастер; осваивать", "/ˈmæstər/", "B1", "It takes years to master a language."),
      w("memory", "память; воспоминание", "/ˈmɛməri/", "B1", "The app uses too much memory."),
      w("proper", "надлежащий, правильный", "/ˈprɑːpər/", "B1", "Use proper names for variables."),
      w("scan", "сканировать; просматривать", "/skæn/", "B1", "Scan the text quickly."),
      w("section", "раздел", "/ˈsɛkʃən/", "A2", "Read the first section of the docs."),
      w("surface", "поверхность", "/ˈsɜːrfəs/", "B1", "Clean the surface of the screen."),
    ],
    it: [
      w("algorithm", "алгоритм", "/ˈælɡərɪðəm/", "C1", "This algorithm sorts the list."),
      w("model", "модель", "/ˈmɑːdəl/", "B1", "The model answers questions."),
      w("dataset", "набор данных", "/ˈdeɪtəsɛt/", "C1", "We need a bigger dataset."),
      w("artificial intelligence", "искусственный интеллект", "/ˌɑːrtɪˈfɪʃəl ɪnˈtɛlɪdʒəns/", "B2", "Artificial intelligence helps us write code."),
      w("machine learning", "машинное обучение", "/məˈʃiːn ˈlɜːrnɪŋ/", "C1", "She works on machine learning."),
    ],
  },
];
